


pluscard.lib:	dbootmsg.obj 	\
		ddisk.obj	\
		dheader.obj	\
		diproc.obj	\
		dplusdrv.obj	\
		droute.obj	\
		drproc.obj	\
		drvins.obj	\
		dsdata.obj	\
		plusdrv.obj	\
		plusmsg.obj
	del pluscard.lib
	lib @libfile
