@echo off
rem
rem Deletes all files created during a build - a required step before
rem building the OAK in a different language.
rem

if "%OAKROOT%"=="" goto error

cd %OAKROOT%


echo Y | del %OAKROOT%\BINARIES\*.*
echo Y | del %OAKROOT%\COMPRESS\*.*

del %OAKROOT%\BIOS\*.OBJ
del %OAKROOT%\BIOS\MSBIO.CL?
del %OAKROOT%\BIOS\MSLOAD.MAP
del %OAKROOT%\BIOS\MSLOAD.COM
del %OAKROOT%\BIOS\MSBIO.MAP
del %OAKROOT%\BIOS\IO.SYS
del %OAKROOT%\BIOS\MSBIO.BIN

del %OAKROOT%\BOOT\BOOT.CL1
del %OAKROOT%\BOOT\MSBOOT.OBJ
del %OAKROOT%\BOOT\MSBOOT.EXE
del %OAKROOT%\BOOT\MSBOOT.BIN
del %OAKROOT%\BOOT\BOOT.INC

del %OAKROOT%\CMD\CPS\REBUILD\*.OBJ
del %OAKROOT%\CMD\CPS\REBUILD\UNFORMAT.MAP
del %OAKROOT%\CMD\CPS\REBUILD\UNFORMAT.EXC
del %OAKROOT%\CMD\CPS\REBUILD\UNFORMAT.PKL
del %OAKROOT%\CMD\CPS\REBUILD\UNFORMAT.COM

del %OAKROOT%\CMD\DOSKEY\*.OBJ
del %OAKROOT%\CMD\DOSKEY\DOSKEY.CL2
del %OAKROOT%\CMD\DOSKEY\DOSKEY.CL1
del %OAKROOT%\CMD\DOSKEY\DOSKEY.EXC
del %OAKROOT%\CMD\DOSKEY\DOSKEY.CO_
del %OAKROOT%\CMD\DOSKEY\DOSKEY.COM

del %OAKROOT%\CMD\FDISK\*.OBJ
del %OAKROOT%\CMD\FDISK\FDISK.CL?
del %OAKROOT%\CMD\FDISK\FDISK5.CL1
del %OAKROOT%\CMD\FDISK\FDBOOT.INC
del %OAKROOT%\CMD\FDISK\FDBOOT.BIN
del %OAKROOT%\CMD\FDISK\FDISKM.C
del %OAKROOT%\CMD\FDISK\FDISK.CTL
del %OAKROOT%\CMD\FDISK\FDISK.MAP
del %OAKROOT%\CMD\FDISK\FDISK.EXE
del %OAKROOT%\CMD\FDISK\FDISK.PKL

del %OAKROOT%\CMD\FORMAT\*.OBJ
del %OAKROOT%\CMD\FORMAT\FORMAT.CL?
del %OAKROOT%\CMD\FORMAT\FORMAT.CTL
del %OAKROOT%\CMD\FORMAT\BOOT.CL1
del %OAKROOT%\CMD\FORMAT\MIR_MAIN.ASM
del %OAKROOT%\CMD\FORMAT\FORMAT.MAP
del %OAKROOT%\CMD\FORMAT\FORMAT.EXE
del %OAKROOT%\CMD\FORMAT\FORMAT.COM

del %OAKROOT%\CMD\KEYB\*.OBJ
del %OAKROOT%\CMD\KEYB\KEYB.CL?
del %OAKROOT%\CMD\KEYB\KEYB.CTL
del %OAKROOT%\CMD\KEYB\KEYB.MAP
del %OAKROOT%\CMD\KEYB\KEYB.EXC
del %OAKROOT%\CMD\KEYB\KEYB.COM

del %OAKROOT%\CMD\MODE\*.OBJ
del %OAKROOT%\CMD\MODE\MODE.CL?
del %OAKROOT%\CMD\MODE\MODE.CTL
del %OAKROOT%\CMD\MODE\MODE.MAP
del %OAKROOT%\CMD\MODE\MODE.EXC
del %OAKROOT%\CMD\MODE\MODE.CO_
del %OAKROOT%\CMD\MODE\MODE.COM

del %OAKROOT%\CMD\SETVER\*.OBJ
del %OAKROOT%\CMD\SETVER\SETVER.MAP
del %OAKROOT%\CMD\SETVER\SETVER.EXE
del %OAKROOT%\CMD\SETVER\SETVER.EX_

del %OAKROOT%\CMD\SORT\*.OBJ
del %OAKROOT%\CMD\SORT\SORT.CL?
del %OAKROOT%\CMD\SORT\SORT.CTL
del %OAKROOT%\CMD\SORT\SORTMES.ASM
del %OAKROOT%\CMD\SORT\SORT.EXE
del %OAKROOT%\CMD\SORT\SORT.EX_

del %OAKROOT%\CMD\SYS\*.OBJ
del %OAKROOT%\CMD\SYS\SYS.CL?
del %OAKROOT%\CMD\SYS\SYS.CTL
del %OAKROOT%\CMD\SYS\SYS.MAP
del %OAKROOT%\CMD\SYS\SYS.EXC
del %OAKROOT%\CMD\SYS\SYS.PKL
del %OAKROOT%\CMD\SYS\SYS.COM

del %OAKROOT%\DEV\ANSI\*.OBJ
del %OAKROOT%\DEV\ANSI\ANSI.CL?
del %OAKROOT%\DEV\ANSI\ANSI.CTL
del %OAKROOT%\DEV\ANSI\ANSI.MAP
del %OAKROOT%\DEV\ANSI\ANSI.EXS
del %OAKROOT%\DEV\ANSI\ANSI.SY_
del %OAKROOT%\DEV\ANSI\ANSI.SYS

del %OAKROOT%\DEV\DISPLAY\*.OBJ
del %OAKROOT%\DEV\DISPLAY\DISPLAY.CL?
del %OAKROOT%\DEV\DISPLAY\DISPLAY.CTL
del %OAKROOT%\DEV\DISPLAY\DISPLAY.SY_
del %OAKROOT%\DEV\DISPLAY\DISPLAY.SYS
del %OAKROOT%\DEV\DISPLAY\EGA\COPYRIGH.OBJ
del %OAKROOT%\DEV\DISPLAY\EGA\EGA.CP_
del %OAKROOT%\DEV\DISPLAY\EGA\EGA.CPI

del %OAKROOT%\DEV\EMM386\EMMMES.OBJ
del %OAKROOT%\DEV\EMM386\EMM386.MAP
del %OAKROOT%\DEV\EMM386\EMM386.EXE
del %OAKROOT%\DEV\EMM386\EMM386.EX_
del %OAKROOT%\DEV\EMM386\LHVXD\EMM386.EXE
del %OAKROOT%\DEV\EMM386\LHVXD\LOADHI.MAP

del %OAKROOT%\DEV\HIMEM\*.OBJ
del %OAKROOT%\DEV\HIMEM\HIMEM.MAP
del %OAKROOT%\DEV\HIMEM\HIMEM.EXE
del %OAKROOT%\DEV\HIMEM\HIMEM.BIN
del %OAKROOT%\DEV\HIMEM\HIMEM.SYS
del %OAKROOT%\DEV\HIMEM\HIMEM.SY_

del %OAKROOT%\DEV\KEYBOARD\*.OBJ
del %OAKROOT%\DEV\KEYBOARD\KEYBOARD.MAP
del %OAKROOT%\DEV\KEYBOARD\KEYBOARD.EXS
del %OAKROOT%\DEV\KEYBOARD\KEYBOARD.SYS

del %OAKROOT%\DEV\POWER\*.OBJ
del %OAKROOT%\DEV\POWER\POWERMSG.INC
del %OAKROOT%\DEV\POWER\POWER.MAP
del %OAKROOT%\DEV\POWER\POWER.EXE
del %OAKROOT%\DEV\POWER\POWER.EX_

del %OAKROOT%\DEV\PRINTER\*.OBJ
del %OAKROOT%\DEV\PRINTER\PRINTER.CL?
del %OAKROOT%\DEV\PRINTER\PRINTER.CTL
del %OAKROOT%\DEV\PRINTER\PRINTER.MAP
del %OAKROOT%\DEV\PRINTER\PRINTER.SY_
del %OAKROOT%\DEV\PRINTER\PRINTER.SYS
del %OAKROOT%\DEV\PRINTER\4201\4201.CP_
del %OAKROOT%\DEV\PRINTER\4208\4208.CP_
del %OAKROOT%\DEV\PRINTER\5202\5202.OBJ
del %OAKROOT%\DEV\PRINTER\5202\5202.CP_
del %OAKROOT%\DEV\PRINTER\5202\5202.CPI

del %OAKROOT%\DOS\MSDOS.CL?
del %OAKROOT%\DOS\MSDATA.OBJ
del %OAKROOT%\DOS\MSDOSME.OBJ
del %OAKROOT%\DOS\ORIGIN.OBJ
del %OAKROOT%\DOS\MSDOS.MAP
del %OAKROOT%\DOS\MSDOS.EXE
del %OAKROOT%\DOS\MSDOS.BIN
del %OAKROOT%\DOS\MSDOS.SYS

del %OAKROOT%\INSTALL\INCLUDE\WINDOW.H
del %OAKROOT%\INSTALL\LIB\LCOMMON.LIB

del %OAKROOT%\INSTALL\LIB\BIOS\*.OBJ
del %OAKROOT%\INSTALL\LIB\BIOS\BIOS_IO.LIB
del %OAKROOT%\INSTALL\LIB\COPY\*.OBJ
del %OAKROOT%\INSTALL\LIB\COPY\FILECOPY.LIB
del %OAKROOT%\INSTALL\LIB\DISK\*.OBJ
del %OAKROOT%\INSTALL\LIB\DISK\TBOOT.ASM
del %OAKROOT%\INSTALL\LIB\DISK\TBOOT.BIN
del %OAKROOT%\INSTALL\LIB\DISK\TBOOT.INC
del %OAKROOT%\INSTALL\LIB\DISK\DISK_IO.LIB
del %OAKROOT%\INSTALL\LIB\FILE\*.OBJ
del %OAKROOT%\INSTALL\LIB\FILE\FILE_IO.LIB
del %OAKROOT%\INSTALL\LIB\HARDWARE\*.OBJ
del %OAKROOT%\INSTALL\LIB\HARDWARE\HARDWARE.LIB
del %OAKROOT%\INSTALL\LIB\HDISK\*.OBJ
del %OAKROOT%\INSTALL\LIB\HDISK\HDISK.LIB
del %OAKROOT%\INSTALL\LIB\PROMPTS\*.OBJ
del %OAKROOT%\INSTALL\LIB\PROMPTS\PROMPTS.LIB
del %OAKROOT%\INSTALL\LIB\STRLIB\*.OBJ
del %OAKROOT%\INSTALL\LIB\STRLIB\STRLIB.LIB
del %OAKROOT%\INSTALL\LIB\WINDOW\*.OBJ
del %OAKROOT%\INSTALL\LIB\WINDOW\WINDOW.LIB

del %OAKROOT%\INSTALL\OEM\*.OBJ
del %OAKROOT%\INSTALL\OEM\AUTOCONF.H
del %OAKROOT%\INSTALL\OEM\CODES.H
del %OAKROOT%\INSTALL\OEM\MESSAGE.TXT
del %OAKROOT%\INSTALL\OEM\MESSAGE.H
del %OAKROOT%\INSTALL\OEM\MESSAGE.ASM
del %OAKROOT%\INSTALL\OEM\INSTALL.INC
del %OAKROOT%\INSTALL\OEM\OEMSETUP.MAP
del %OAKROOT%\INSTALL\OEM\SETUP.EXE

del %OAKROOT%\MESSAGES\%COUNTRY%.MSG
del %OAKROOT%\MESSAGES\%COUNTRY%.IDX

del %OAKROOT%\MKIMAGE\*.OBJ
del %OAKROOT%\MKIMAGE\MKIMAGE.EXE

goto done

:error
echo ERROR : You must run OAKENV.BAT first to set up the correct build
echo     environment before you can run this batch file.  OAKENV.BAT is
echo     located in the root directory of the OAK tree.

:done

