;
;       Microsoft Confidential
;       Copyright (C) Microsoft Corporation 1981-1991
;       All Rights Reserved.
;
;       Internal CONFIG.SYS constants, structures, etc.
;

CONFIG_BEGIN        =   '['
CONFIG_BREAK        =   'C'
CONFIG_BUFFERS      =   'B'
CONFIG_COMMENT      =   'Y'
CONFIG_COUNTRY      =   'Q'
CONFIG_DEVICE       =   'D'
CONFIG_DEVICEHIGH   =   'U'
CONFIG_DOS          =   'H'
CONFIG_DRIVPARM     =   'P'
CONFIG_FCBS         =   'X'
CONFIG_FILES        =   'F'
CONFIG_INCLUDE      =   'J'
CONFIG_INSTALL      =   'I'
CONFIG_INSTALLHIGH  =   'W'
CONFIG_LASTDRIVE    =   'L'
CONFIG_MENUCOLOR    =   'R'
CONFIG_MENUDEFAULT  =   'A'
CONFIG_MENUITEM     =   'E'
CONFIG_MULTITRACK   =   'M'
CONFIG_NUMLOCK      =   'N'
CONFIG_REM          =   '0'
CONFIG_SEMICOLON    =   ';'
CONFIG_SET          =   'V'
CONFIG_SHELL        =   'S'
CONFIG_STACKS       =   'K'
CONFIG_SUBMENU      =   'O'
CONFIG_SWITCHES     =   '1'

CONFIG_UNKNOWN      =   'Z'

CONFIG_OPTION_QUERY =   80h
