;***
;ascii.inc - 20-Mar-86 - ASCII Character Definitions
;***
	.XLIST
;***
;
;	Copyright <C> 1986, Microsoft Corporation
;
;Purpose:
;
;******************************************************************************

ASCBEL=	07h			;Bell
ASCBS=	08h			;Backspace
ASCHT=	09h			;Tab
ASCLF=	0Ah			;Line feed
ASCCR=	0Dh			;Carriage return
ASCSP=	20h			;Space
ASCQO=	22h			;Quote

newline= asccr

	.LIST
