# Makefile for mem.lib
#
inc =..\..\inc
doslib  =..
#
#
#######################	dependencies begin here. #########################
#

all:         $(doslib)\mem.lib

clean:

$(doslib)\mem.lib: mem.lib
              copy mem.lib $(doslib)
