all:
        cd inc
        $(MAKE)
        cd ..\loader
        $(MAKE)
        cd ..\iniparse
        $(MAKE)
        cd ..\shell
        $(MAKE)
        cd ..\swapper
        $(MAKE)
        cd ..\vids
        $(MAKE)
        cd ..\inis
        $(MAKE)
        cd ..\grbs
        $(MAKE)
        cd ..\hlps
        $(MAKE)
        cd ..
