all:
    cd inc
        $(MAKE)
    cd ..\loader
        $(MAKE)
    cd ..\iniparse
        $(MAKE)
    cd ..\shell
        $(MAKE)
    cd ..\swapper
        $(MAKE)
    cd ..\vids
        $(MAKE)
    cd ..\inis
        $(MAKE)
    cd ..\grbs
        $(MAKE)
    cd ..\hlps
        $(MAKE)
    cd ..

clean:
    cd inc
        nmake clean
    cd ..\loader
        nmake clean
    cd ..\iniparse
        nmake clean
    cd ..\shell
        nmake clean
    cd ..\swapper
        nmake clean
    cd ..\vids
        nmake clean
    cd ..\inis
        nmake clean
    cd ..\grbs
        nmake clean
    cd ..\hlps
        nmake clean
    cd ..