"Error 0",
"",
"No such file or directory",
"",
"",
"",
"",
"Arg list too long",
"Exec format error",
"Bad file number",
"",
"",
"Not enough core",
"Permission denied",
"",
"",
"",
"File exists",
"Cross-device link",
"",
"",
"",
"Invalid argument",
"",
"Too many open files",
"",
"",
"",
"No space left on device",
"",
"",
"",
"",
"Math argument",
"Result too large",
"",
"Resource deadlock would occur",
"Unknown error"












