;/*
; *                      Microsoft Confidential
; *                      Copyright (C) Microsoft Corporation 1991
; *                      All Rights Reserved.
; */

;
;----------------------------------------------------------------------------
;
; M026	: B#5794. Updated DOS_SIZE.
;
;----------------------------------------------------------------------------
;
	%out ..filesize.inc

BIOS_SIZE	equ	 35000		;actually
DOS_SIZE	equ	 38000		;actually M026
