0029
COMMON   00000006 0038
0001 U 0000 "Incorrect DOS version",CR,LF
0002 U 0000 "%1 already installed",CR,LF
0003 U 0000 "%1 bytes available on disk",CR,LF
0004 U 0000 "%1 bytes free",CR,LF
0005 U 0000 "%1 bytes in bad sectors",CR,LF
0006 U 0000 "%1 bytes total disk space",CR,LF
0007 U 0000 "%1 bytes total memory",CR,LF
0008 U 0000 "%1 bytes used by system",CR,LF
0009 U 0000 "%1 installed",CR,LF
0010 U 0000 "%1 not installed",CR,LF
0011 U 0000 "%1 not installed",CR,LF
0012 U 0000 "Cannot %1 a network drive",CR,LF
0013 U 0000 "",
0014 U 0000 "Cannot %1 a SUBSTed or ASSIGNed drive",CR,LF
0015 U 0000 "Cannot execute %1",CR,LF
0016 U 0000 "Expanded Memory not available",CR,LF
0017 U 0000 "File allocation table bad, drive %1",CR,LF
0018 U 0000 "File cannot be copied onto itself",CR,LF
0019 U 0000 "Insert target disk in drive %1",CR,LF
0020 U 0000 "Insufficient disk space",CR,LF
0021 U 0000 "Invalid characters in volume label",CR,LF
0022 U 0000 "Invalid code page",CR,LF
0023 U 0000 "Invalid date",CR,LF
0024 U 0000 "Invalid time",CR,LF
0025 U 0000 "Invalid path",CR,LF
0026 U 0000 "No source drive specified",CR,LF
0027 U 0000 "No target drive specified",CR,LF
0028 U 0000 "Press any key to continue . . .",CR,LF
0029 U 0000 "Source path required",CR,LF
0030 U 0000 "System transferred",CR,LF
0031 U 0000 "",
0032 U 0000 "Unable to create directory",CR,LF
0033 U 0000 "Volume in drive %1 has no label",CR,LF
0034 U 0000 "Volume in drive %1 is %2",CR,LF
0035 U 0001 "Volume label (11 characters, ENTER for none)? "
0036 U 0000 "Volume Serial Number is %1-%2",CR,LF
0037 U 0000 "Incorrect file type",CR,LF
0038 U 0001 CR,LF
EXTEND   00000689 0090
0001 U 0003 "Invalid function"
0002 U 0000 "File not found"
0003 U 0000 "Path not found"
0004 U 0000 "Too many open files"
0005 U 0000 "Access denied "
0006 U 0000 "Invalid handle"
0007 U 0000 "Memory control blocks destroyed"
0008 U 0000 "Insufficient memory"
0009 U 0000 "Invalid memory block address"
0010 U 0000 "Invalid Environment"
0011 U 0000 "Invalid format"
0012 U 0000 "Invalid function parameter"
0013 U 0000 "Invalid data"
0014 U 0000 "",
0015 U 0000 "Invalid drive specification"
0016 U 0000 "Attempt to remove current directory"
0017 U 0000 "Not same device"
0018 U 0000 "No more files"
0019 U 0000 "Write protect error"
0020 U 0000 "Invalid unit"
0021 U 0000 "Not ready"
0022 U 0000 "Invalid device request"
0023 U 0000 "Data error"
0024 U 0000 "Invalid device request parameters"
0025 U 0000 "Seek error"
0026 U 0000 "Invalid media type"
0027 U 0000 "Sector not found"
0028 U 0000 "Printer out of paper error"
0029 U 0000 "Write fault error"
0030 U 0000 "Read fault error"
0031 U 0000 "General failure"
0032 U 0000 "Sharing violation"
0033 U 0000 "Lock violation"
0034 U 0000 "Invalid disk change"
0035 U 0000 "FCB unavailable"
0036 U 0000 "System resource exhausted"
0037 U 0000 "Code page mismatch"
0038 U 0000 "Out of input"
0039 U 0000 "Insufficient disk space"
0040 U 0000 "",
0041 U 0000 "",
0042 U 0000 "",
0043 U 0000 "",
0044 U 0000 "",
0045 U 0000 "",
0046 U 0000 "",
0047 U 0000 "",
0048 U 0000 "",
0049 U 0000 "",
0050 U 0000 "NET809: Network request not supported"
0051 U 0000 "NET801: Remote computer not listening"
0052 U 0000 "NET802: Duplicate name on network"
0053 U 0000 "NET803: Network path not found"
0054 U 0000 "NET804: Network busy"
0055 U 0000 "NET805: Network device no longer exists"
0056 U 0000 "NET806: NETBIOS command limit exceeded"
0057 U 0000 "NET807: System error; NETBIOS error"
0058 U 0000 "NET808: Incorrect response from network"
0059 U 0000 "NET810: Unexpected network error"
0060 U 0000 "NET811: Incompatible remote adapter"
0061 U 0000 "NET812: Print queue full"
0062 U 0000 "NET813: Not enough space for print file"
0063 U 0000 "NET814: Print file was cancelled"
0064 U 0000 "NET815: Network name was deleted"
0065 U 0000 "Access denied"
0066 U 0000 "NET817: Network device type incorrect"
0067 U 0000 "NET818: Network name not found"
0068 U 0000 "NET819: Network name limit exceeded"
0069 U 0000 "NET820: NETBIOS session limit exceeded"
0070 U 0000 "NET821: Sharing temporarily paused"
0071 U 0000 "NET823: Network request not accepted"
0072 U 0000 "NET822: Print or disk redirection is paused"
0073 U 0000 "NET476: Netbeui not loaded"
0074 U 0000 "NET477: Unexpected adapter close"
0075 U 0000 "",
0076 U 0000 "",
0077 U 0004 "",
0078 U 0004 "",
0079 U 0004 "",
0080 U 0004 "File exists"
0081 U 0004 "",
0082 U 0004 "Cannot make directory entry"
0083 U 0004 "Fail on INT 24"
0084 U 0004 "Too many redirections"
0085 U 0004 "Duplicate redirection"
0086 U 0004 "Invalid password"
0087 U 0004 "Invalid parameter"
0088 U 0004 "Network data fault"
0089 U 0004 "Function not supported by network"
0090 U 0002 "Required system component not installed"
PARSE    0000131d 0011
0001 U 0000 "Too many parameters"
0002 U 0000 "Required parameter missing"
0003 U 0000 "Invalid switch"
0004 U 0000 "Invalid keyword"
0005 U 0000 "",
0006 U 0000 "Parameter value not in allowed range"
0007 U 0000 "Parameter value not allowed"
0008 U 0000 "Parameter value not allowed"
0009 U 0000 "Parameter format not correct"
0010 U 0000 "Invalid parameter"
0011 U 0000 "Invalid parameter combination"
COMMAND  000014d4 0147
1002 U 0000 "Duplicate file name or file not found",CR,LF
1003 U 0000 "Invalid path or file name",CR,LF
1007 U 0000 "Out of environment space",CR,LF
1008 U 0000 "File creation error",CR,LF
1009 U 0000 "Batch file missing",CR,LF
1010 U 0000 CR,LF,"Insert disk with batch file",CR,LF
1011 U 0000 "Bad command or file name",CR,LF
1016 U 0000 "Content of destination lost before copy",CR,LF
1017 U 0000 "Invalid filename or file not found",CR,LF
1018 U 0000 "%1 file(s) copied",CR,LF
1019 U 0000 "%1 file(s) "
1022 U 0000 "Code page %1 not prepared for system",CR,LF
1023 U 0000  "Code page %1 not prepared for all devices",CR,LF
1024 U 0000 "Active code page: %1",CR,LF
1025 U 0000 "NLSFUNC not installed",CR,LF
1027 U 0000 "Current drive is no longer valid"
1029 U 0000 "Label not found",CR,LF
1030 U 0000 "Syntax error",CR,LF
1032 U 0000 "Current date is %1 %2",CR,LF
1033 U 0000 "SunMonTueWedThuFriSat"
1034 U 0000 "Enter new date (%1): "
1036 U 0000 "Current time is %1",CR,LF
1037 U 0000 "Enter new time: "
1038 U 0000 ",    Delete (Y/N)?"
1039 U 0000 "All files in directory will be deleted!",CR,LF,"Are you sure (Y/N)?"
1040 U 0000 "MS-DOS Version %1.%2"
1044 U 0000 "Invalid directory",CR,LF
1046 U 0000 "Invalid path, not directory,",CR,LF,"or directory not empty",CR,LF
1047 U 0000 "Must specify ON or OFF",CR,LF
1048 U 0000 "Directory of %1",CR,LF
1049 U 0000 "No Path",CR,LF
1050 U 0000 "Invalid drive in search path",CR,LF
1051 U 0000 "Invalid device",CR,LF
1052 U 0000 "FOR cannot be nested",CR,LF
1053 U 0000 "Intermediate file error during pipe",CR,LF
1054 U 0000 "Cannot do binary reads from a device",CR,LF
1055 U 0000 "BREAK is %1",CR,LF
1056 U 0000 "VERIFY is %1",CR,LF
1057 U 0000 "ECHO is %1",CR,LF
1059 U 0000 "off",0
1060 U 0000 "on",0
1061 U 0000 "Error writing to device",CR,LF
1063 U 0000 "%1"
1064 U 0000 "%1"
1065 U 0000 "%1"
1066 U 0000 "%1"
1067 U 0000 9
1068 U 0000 " <DIR>    "
1069 U 0000 8," ",8
1070 U 0000 CR,LF
1071 U 0000 "%1"
1072 U 0000 "mm-dd-yy"
1073 U 0000 "dd-mm-yy"
1074 U 0000 "yy-mm-dd"
1075 U 0000 "%1 %2"
1076 U 0000 "%1"
1077 U 0000 " %1  %2"
1078 U 0000 "Directory already exists",CR,LF
1079 U 0000 "%1 bytes",CR,LF
1080 U 0000 "Total files listed:",CR,LF
1081 U 0000 "(Error occurred in environment variable)",CR,LF
1084 U 0000 "(continuing %1)"
1090 U 0000 "Revision %1",CR,LF
1091 U 0000 "DOS is in ROM"
1092 U 0000 "DOS is in HMA"
1093 U 0000 "DOS is in low memory"
1094 U 0000 "Cannot Loadhigh batch file",CR,LF
1095 U 0000 "LoadHigh: Invalid filename",CR,LF
1096 U 0000 "Cannot open specified country information file",CR,LF
1300 U 0000 "Sets or clears extended CTRL+C checking.",CR,LF,CR,LF
	"BREAK [ON | OFF]",CR,LF,CR,LF
	"Type BREAK without a parameter to display the current BREAK setting.",CR,LF
1320 U 0000 "Displays or sets the active code page number.",CR,LF,CR,LF
	"CHCP [nnn]",CR,LF,CR,LF
1321 U 0000 "  nnn   Specifies a code page number.",CR,LF,CR,LF
	"Type CHCP without a parameter to display the active code page number.",CR,LF
1340 U 0000 "Displays the name of or changes the current directory.",CR,LF,CR,LF
	"CHDIR [drive:][path]",CR,LF
	"CHDIR[..]",CR,LF
1341 U 0000 "CD [drive:][path]",CR,LF
	"CD[..]",CR,LF,CR,LF
	"  ..   Specifies that you want to change to the parent directory.",CR,LF,CR,LF
1342 U 0000 "Type CD drive: to display the current directory in the specified drive.",CR,LF
	"Type CD without parameters to display the current drive and directory.",CR,LF
1360 U 0000 "Clears the screen.",CR,LF,CR,LF
	"CLS",CR,LF
1400 U 0000 "Copies one or more files to another location.",CR,LF,CR,LF
	"COPY [/A | /B] source [/A | /B] [+ source [/A | /B] [+ ...]] [destination",CR,LF
	"  [/A | /B]] [/V]",CR,LF,CR,LF
1401 U 0000 "  source       Specifies the file or files to be copied.",CR,LF
	"  /A           Indicates an ASCII text file.",CR,LF
1402 U 0000 "  /B           Indicates a binary file.",CR,LF
	"  destination  Specifies the directory and/or filename for the new file(s).",CR,LF
1403 U 0000 "  /V           Verifies that new files are written correctly.",CR,LF,CR,LF
1404 U 0000 "To append files, specify a single file for destination, but multiple files",CR,LF
	"for source (using wildcards or file1+file2+file3 format).",CR,LF
1420 U 0000 "Changes the terminal device used to control your system.",CR,LF,CR,LF
	"CTTY device",CR,LF,CR,LF
	"  device   The terminal device you want to use, such as COM1.",CR,LF
1440 U 0000 "Displays or sets the date.",CR,LF,CR,LF
	"DATE [date]",CR,LF,CR,LF
1441 U 0000 "Type DATE without parameters to display the current date setting and",CR,LF
	"a prompt for a new one.  Press ENTER to keep the same date.",CR,LF
1460 U 0000 "Deletes one or more files.",CR,LF,CR,LF
	"DEL [drive:][path]filename [/P]",CR,LF
	"ERASE [drive:][path]filename [/P]",CR,LF,CR,LF
1461 U 0000 "  [drive:][path]filename  Specifies the file(s) to delete.  Specify multiple",CR,LF
	"                          files by using wildcards.",CR,LF
1462 U 0000 "  /P                      Prompts for confirmation before deleting each file.",CR,LF
1480 U 0000 "Displays a list of files and subdirectories in a directory.",CR,LF,CR,LF
	"DIR [drive:][path][filename] [/P] [/W] [/A[[:]attributes]]",CR,LF
	"  [/O[[:]sortorder]] [/S] [/B] [/L]",CR,LF,CR,LF
1481 U 0000 "  [drive:][path][filename]",CR,LF
	"              Specifies drive, directory, and/or files to list.",CR,LF
1482 U 0000 "  /P          Pauses after each screenful of information.",CR,LF
	"  /W          Uses wide list format.",CR,LF
1483 U 0000 "  /A          Displays files with specified attributes.",CR,LF
	"  attributes   D  Directories                R  Read-only files",CR,LF
1484 U 0000 "               H  Hidden files               A  Files ready for archiving",CR,LF
	"               S  System files               -  Prefix meaning ""not""",CR,LF
	"  /O          List by files in sorted order.",CR,LF
1485 U 0000 "  sortorder    N  By name (alphabetic)       S  By size (smallest first)",CR,LF
	"               E  By extension (alphabetic)  D  By date & time (earliest first)",CR,LF
1486 U 0000 "               G  Group directories first    -  Prefix to reverse order",CR,LF
	"  /S          Displays files in specified directory and all subdirectories.",CR,LF
1487 U 0000 "  /B          Uses bare format (no heading information or summary).",CR,LF
	"  /L          Uses lowercase.",CR,LF,CR,LF
1488 U 0000 "Switches may be preset in the DIRCMD environment variable.  Override",CR,LF
	"preset switches by prefixing any switch with - (hyphen)--for example, /-W.",CR,LF
1500 U 0000 "Quits the COMMAND.COM program (command interpreter).",CR,LF,CR,LF
	"EXIT",CR,LF
1520 U 0000 "Creates a directory.",CR,LF,CR,LF
	"MKDIR [drive:]path",CR,LF
	"MD [drive:]path",CR,LF
1540 U 0000 "Displays or sets a search path for executable files.",CR,LF,CR,LF
	"PATH [[drive:]path[;...]]",CR,LF
	"PATH ;",CR,LF,CR,LF
1541 U 0000 "Type PATH ; to clear all search-path settings and direct MS-DOS to search",CR,LF
	"only in the current directory.",CR,LF
1542 U 0000 "Type PATH without parameters to display the current path.",CR,LF
1560 U 0000 "Changes the MS-DOS command prompt.",CR,LF,CR,LF
	"PROMPT [text]",CR,LF,CR,LF
1561 U 0000 "  text    Specifies a new command prompt.",CR,LF,CR,LF
	"Prompt can be made up of normal characters and the following special codes:",CR,LF,CR,LF
1562 U 0000 "  $Q   = (equal sign)",CR,LF
	"  $$   $ (dollar sign)",CR,LF
1563 U 0000 "  $T   Current time",CR,LF
	"  $D   Current date",CR,LF
1564 U 0000 "  $P   Current drive and path",CR,LF
	"  $V   MS-DOS version number",CR,LF
1565 U 0000 "  $N   Current drive",CR,LF
	"  $G   > (greater-than sign)",CR,LF
1566 U 0000 "  $L   < (less-than sign)",CR,LF
	"  $B   | (pipe)",CR,LF
1567 U 0000 "  $H   Backspace (erases previous character)",CR,LF
	"  $E   Escape code (ASCII code 27)",CR,LF
	"  $_   Carriage return and linefeed",CR,LF,CR,LF
1568 U 0000 "Type PROMPT without parameters to reset the prompt to the default setting.",CR,LF
1580 U 0000 "Removes (deletes) a directory.",CR,LF,CR,LF
	"RMDIR [drive:]path",CR,LF
	"RD [drive:]path",CR,LF
1600 U 0000 "Renames a file or files.",CR,LF,CR,LF
1601 U 0000 "RENAME [drive:][path]filename1 filename2",CR,LF
	"REN [drive:][path]filename1 filename2",CR,LF,CR,LF
1602 U 0000 "Note that you cannot specify a new drive or path for your destination file.",CR,LF
1620 U 0000 "Displays, sets, or removes MS-DOS environment variables.",CR,LF,CR,LF
	"SET [variable=[string]]",CR,LF,CR,LF
1621 U 0000 "  variable  Specifies the environment-variable name.",CR,LF
	"  string    Specifies a series of characters to assign to the variable.",CR,LF,CR,LF
1622 U 0000 "Type SET without parameters to display the current environment variables.",CR,LF
1640 U 0000 "Displays or sets the system time.",CR,LF,CR,LF
	"TIME [time]",CR,LF,CR,LF
1641 U 0000 "Type TIME with no parameters to display the current time setting and a prompt",CR,LF
	"for a new one.  Press ENTER to keep the same time.",CR,LF
1660 U 0000 "Displays the contents of a text file.",CR,LF,CR,LF
	"TYPE [drive:][path]filename",CR,LF
1680 U 0000 "Displays the MS-DOS version.",CR,LF,CR,LF
	"VER",CR,LF
1700 U 0000 "Tells MS-DOS whether to verify that your files are written correctly to a",CR,LF
	"disk.",CR,LF,CR,LF
	"VERIFY [ON | OFF]",CR,LF,CR,LF
	"Type VERIFY without a parameter to display the current VERIFY setting.",CR,LF
1720 U 0000 "Displays the disk volume label and serial number, if they exist.",CR,LF,CR,LF
	"VOL [drive:]",CR,LF
1740 U 0000 "Calls one batch program from another.",CR,LF,CR,LF
	"CALL [drive:][path]filename [batch-parameters]",CR,LF,CR,LF
1741 U 0000 "  batch-parameters   Specifies any command-line information required by the",CR,LF
	"                     batch program.",CR,LF
1760 U 0000 "Records comments (remarks) in a batch file or CONFIG.SYS.",CR,LF,CR,LF
	"REM [comment]",CR,LF
1780 U 0000 "Suspends processing of a batch program and displays the message ""Press any",CR,LF
	"key to continue....""",CR,LF,CR,LF
	"PAUSE",CR,LF
1800 U 0000 "Displays messages, or turns command-echoing on or off.",CR,LF,CR,LF
	"  ECHO [ON | OFF]",CR,LF
1801 U 0000 "  ECHO [message]",CR,LF,CR,LF
	"Type ECHO without parameters to display the current echo setting.",CR,LF
1820 U 0000 "Directs MS-DOS to a labelled line in a batch program.",CR,LF,CR,LF
	"GOTO label",CR,LF,CR,LF
1821 U 0000 "  label   Specifies a text string used in the batch program as a label.",CR,LF,CR,LF
	"You type a label on a line by itself, beginning with a colon.",CR,LF
1840 U 0000 "Changes the position of replaceable parameters in a batch file.",CR,LF,CR,LF
	"SHIFT",CR,LF
1860 U 0000 "Performs conditional processing in batch programs.",CR,LF,CR,LF
	"IF [NOT] ERRORLEVEL number command",CR,LF
1861 U 0000 "IF [NOT] string1==string2 command",CR,LF
	"IF [NOT] EXIST filename command",CR,LF,CR,LF
1862 U 0000 "  NOT               Specifies that MS-DOS should carry out the command only",CR,LF
	"                    if the condition is false.",CR,LF
1863 U 0000 "  ERRORLEVEL number Specifies a true condition if the last program run returned",CR,LF
	"                    an exit code equal to or greater than the number specified.",CR,LF
1864 U 0000 "  command           Specifies the command to carry out if the condition is",CR,LF
	"                    met.",CR,LF
1865 U 0000 "  string1==string2  Specifies a true condition if the specified text strings",CR,LF
	"                    match.",CR,LF
1866 U 0000 "  EXIST filename    Specifies a true condition if the specified filename",CR,LF
	"                    exists.",CR,LF
1880 U 0000 "Runs a specified command for each file in a set of files.",CR,LF,CR,LF
	"FOR %variable IN (set) DO command [command-parameters]",CR,LF,CR,LF
1881 U 0000 "  %variable  Specifies a replaceable parameter.",CR,LF
	"  (set)      Specifies a set of one or more files.  Wildcards may be used.",CR,LF
1882 U 0000 "  command    Specifies the command to carry out for each file.",CR,LF
	"  command-parameters",CR,LF
1883 U 0000 "             Specifies parameters or switches for the specified command.",CR,LF,CR,LF
	"To use the FOR command in a batch program, specify %%variable instead of",CR,LF
	"%variable.",CR,LF
1900 U 0000 "Reserved command name",CR,LF
1920 U 0000 "Loads a program into the upper memory area.",CR,LF,CR,LF
1921 U 0000 "LOADHIGH [drive:][path]filename [parameters]",CR,LF
	"LH [drive:][path]filename [parameters]",CR,LF,CR,LF
1922 U 0000 "  parameters   Specifies any command-line information required by the",CR,LF
	"               program you want to load.",CR,LF
ANSI     000046c0 0001
0010 U 0000 "Invalid parameter - %1",CR,LF
APPEND   00004704 0026
0001 U 0000 "Incorrect APPEND version",CR,LF
0002 U 0000 "Invalid path",CR,LF
0003 U 0000 "Invalid parameter",CR,LF
0004 U 0000 "Invalid combination of parameters",CR,LF
0005 U 0000 "No Append",CR,LF
0006 U 0000 "APPEND / ASSIGN Conflict",CR,LF
0007 U 0000 "APPEND / TopView Conflict",CR,LF
0008 U 0000 "Incorrect DOS version",CR,LF
0009 U 0000 "APPEND already installed",CR,LF
0300 U 0000 "Allows programs to open data files in specified directories as if they were in",CR,LF
0301 U 0000 "the current directory.",CR,LF,CR,LF
0302 U 0000 "APPEND [[drive:]path[;...]] [/X[:ON | :OFF]] [/PATH:ON | /PATH:OFF] [/E]",CR,LF
0303 U 0000 "APPEND ;",CR,LF,CR,LF
0304 U 0000 "  [drive:]path Specifies a drive and directory to append.",CR,LF
0305 U 0000 "  /X:ON        Applies appended directories to file searches and",CR,LF
0306 U 0000 "               application execution.",CR,LF
0307 U 0000 "  /X:OFF       Applies appended directories only to requests to open files.",CR,LF
0308 U 0000 "               /X:OFF is the default setting.",CR,LF
0309 U 0000 "  /PATH:ON     Applies appended directories to file requests that already",CR,LF
0310 U 0000 "               specify a path.  /PATH:ON is the default setting.",CR,LF
0311 U 0000 "  /PATH:OFF    Turns off the effect of /PATH:ON.",CR,LF
0312 U 0000 "  /E           Stores a copy of the appended directory list in an environment",CR,LF
0313 U 0000 "               variable named APPEND.  /E may be used only the first time",CR,LF
0314 U 0000 "               you use APPEND after starting your system.",CR,LF,CR,LF
0315 U 0000 "Type APPEND ; to clear the appended directory list.",CR,LF
0316 U 0000 "Type APPEND without parameters to display the appended directory list.",CR,LF
BACKUP   00004df2 0040
0002 U 0000 CR,LF,"Insufficient memory",CR,LF
0006 U 0000 CR,LF,"Invalid drive specification",CR,LF
0014 U 0000 CR,LF,"Source and target drives are the same",CR,LF
0015 U 0001 CR,LF,"Error executing FORMAT",CR,LF
0016 U 0001 CR,LF,"Cannot find FORMAT.COM",CR,LF
0017 U 0000 CR,LF,"Error opening logfile",CR,LF
0018 U 0000 CR,LF,"Logging to file %1",CR,LF
0019 U 0000 CR,LF,"Last backup diskette not inserted",CR,LF
0020 U 0000 CR,LF,"WARNING! Files in the target drive",CR,LF
	"%1:\ root directory will be erased",CR,LF
0021 U 0000 CR,LF,"WARNING! Files in the target drive",CR,LF
	"%1:\BACKUP directory will be erased",CR,LF
0022 U 0000 CR,LF,"*** Backing up files to drive %1: ***",CR,LF
0023 U 0000 "Diskette Number: %1",CR,LF
0024 U 0000 CR,LF,"WARNING! No files were found to back up",CR,LF
0025 U 0000 CR,LF,"Insert backup source diskette in drive %1:",CR,LF
0026 U 0000 CR,LF,"Insert backup diskette %1 in drive %2:",CR,LF
0027 U 0000 CR,LF,"*** Not able to backup file ***",CR,LF
0028 U 0000 CR,LF,"Insert last backup diskette in drive %1:",CR,LF
0029 U 0000 CR,LF,"Target cannot be used for backup",CR,LF
0030 U 0000 CR,LF,"*** Last file not backed up ***",CR,LF
0031 U 0000 CR,LF,"Fixed backup device %1: is full",CR,LF
0032 U 0000 CR,LF,"Disk full error writing to BACKUP Log File",CR,LF
0034 U 0000 CR,LF
0035 U 0001 CR,LF,"Cannot FORMAT nonremovable drive %1:",CR,LF
0040 U 0000 CR, LF, "Because your source drive is either ASSIGNed, JOINed, or SUBSTed", CR, LF, "it is actually the same as the target drive", CR, LF
0041 U 0000 CR, LF, "Because your target drive is either ASSIGNed, JOINed, or SUBSTed", CR, LF, "it is actually the same as the source drive", CR, LF
0042 U 0000 "Your target diskette is unformatted and "
0043 U 0000 "No FORMAT program was found.",CR,LF
	"Do you have another diskette with FORMAT on it (Y/N)? "
0044 U 0000 CR,LF,"Insert the diskette with FORMAT in drive A:",CR,LF
0045 U 0000 CR,LF,"Do you want to continue by inserting a new disk (Y/N)? "
0300 U 0000 "Backs up one or more files from one disk to another.",CR,LF,CR,LF
0301 U 0000 "BACKUP source destination-drive: [/S] [/M] [/A] [/F[:size]]",CR,LF
	"  [/D:date[/T:time]] [/L[:[drive:][path]logfile]]",CR,LF,CR,LF
0302 U 0000 "  source             Specifies the file(s), drive, or directory to back up.",CR,LF
0303 U 0000 "  destination-drive: Specifies the drive to save backup copies onto.",CR,LF
0304 U 0000 "  /S                 Backs up contents of subdirectories.",CR,LF
0305 U 0000 "  /M                 Backs up only files that have changed since the last",CR,LF
	"                     backup.",CR,LF
0306 U 0000 "  /A                 Adds backup files to an existing backup disk.",CR,LF
0307 U 0000 "  /F:[size]          Specifies the size of the disk to be formatted.",CR,LF
0308 U 0000 "  /D:date            Backs up only files changed on or after the specified",CR,LF
	"                     date.",CR,LF
0309 U 0000 "  /T:time            Backs up only files changed at or after the specified",CR,LF
	"                     time.",CR,LF
0310 U 0000 "  /L[:[drive:][path]logfile]",CR,LF
	"                     Creates a log file and entry to record the backup",CR,LF
	"                     operation.",CR,LF
DEBUG    00005aca 0068
0004 U 0000 "Allocation failed or specified buffer too small",CR,LF
0006 U 0000 "Bad device name"
0007 U 0000 "Cannot open list device PRN",CR,LF
	"Enter name of list device? "
0008 U 0000 CR,LF
0009 U 0000 CR,LF,"Program terminated normally",CR,LF
0010 U 0001 "Invalid drive specification",CR,LF
0012 U 0001 "File creation error",CR,LF
0013 U 0001 "Insufficient space on disk",CR,LF
0014 U 0001 "Disk error reading drive %1",CR,LF
0015 U 0001 "Disk error writing drive %1",CR,LF
0016 U 0001 "Write protect error reading drive %1",CR,LF
0017 U 0001 "Write protect error writing drive %1",CR,LF
0019 U 0000 "%1^ Error"
0020 U 0001 "Error in EXE or HEX file",CR,LF
0021 U 0001 "EXE and HEX files cannot be written",CR,LF
0022 U 0000 "EXEC failure"
0023 U 0001 "(W)rite error, no destination defined",CR,LF
0024 U 0001 "Access denied",CR,LF
0025 U 0000 "Parity error or nonexistent memory error detected"
0026 U 0000 "-"
0027 U 0000 "%1 -"
0032 U 0000 "%1%2"
0033 U 0000 "%1:%2 %3"
0034 U 0000 "%1  %2"
0035 U 0000 "%1 %2",CR,LF,":"
0036 U 0000 "%1=%2  "
0037 U 0000 "%1 Error"
0038 U 0000 "Writing %2%1 bytes"                                      ;C02
0039 U 0000 "%1:%2="
0040 U 0000 "%1"
0041 U 0000 "%1"
0042 U 0000 "%1:%2  %3  %4  %5:%6"
0044 U 0000 32,8
0046 U 0000 "%1"
0047 U 0000 "%1"
0050 U 0000 "%1 of a total %2 EMS pages have been allocated",cr,lf
0051 U 0000 "%1 of a total %2 EMS handles have been allocated",cr,lf
0055 U 0000 "Handle created = %1 ",cr,lf
0056 U 0000 "Logical page %1 mapped to physical page %2 ",cr,lf
0057 U 0001 "EMS hardware/software failure",cr,lf
0058 U 0000 "Handle not found",cr,lf
0059 U 0000 "Invalid function code",cr,lf
0060 U 0000 "No free handles",cr,lf
0061 U 0000 "Save/Restore error",cr,lf
0062 U 0000 "Total pages exceeded",cr,lf
0063 U 0000 "Free pages exceeded",cr,lf
0064 U 0000 "Parameter error",cr,lf
0065 U 0000 "Logical Page out of range",cr,lf
0066 U 0000 "Physical Page out of range",cr,lf
0067 U 0000 "Save area already in use",cr,lf
0068 U 0000 "Save area not in use",cr,lf
0070 U 0001 "General EMS error",cr,lf
0071 U 0000 "Missing or invalid EMS parameter",cr,lf
0072 U 0000 "Handle %1 has %2 pages allocated",cr,lf
0075 U 0000 "Physical page %1 = Frame segment %2",cr,lf
0076 U 0003 "Handle %1 deallocated",cr,lf
0078 U 0000 "EMS not installed",cr,lf
0090 U 0000 "Runs Debug, a program testing and editing tool.",cr,lf,cr,lf
0091 U 0000 "DEBUG [[drive:][path]filename [testfile-parameters]]",cr,lf,cr,lf
0092 U 0000 "  [drive:][path]filename  Specifies the file you want to test.", cr,lf
0093 U 0000 "  testfile-parameters     Specifies command-line information required by",cr,lf
	"                          the file you want to test.",cr,lf,cr,lf
0094 U 0000 "After Debug starts, type ? to display a list of debugging commands.",cr,lf
0100 U 0000 "assemble     A [address]",CR,LF
	"compare      C range address",CR,LF
	"dump         D [range]",CR,LF
	"enter        E address [list]",CR,LF
0101 U 0000 "fill         F range list",CR,LF
	"go           G [=address] [addresses]",CR,LF
	"hex          H value1 value2",CR,LF
	"input        I port",CR,LF
0102 U 0000 "load         L [address] [drive] [firstsector] [number]",CR,LF
	"move         M range address",CR,LF
	"name         N [pathname] [arglist]",CR,LF
	"output       O port byte",CR,LF
0103 U 0000 "proceed      P [=address] [number]",CR,LF
	"quit         Q",CR,LF
	"register     R [register]",CR,LF
	"search       S range list",CR,LF
0104 U 0000 "trace        T [=address] [value]",CR,LF
	"unassemble   U [range]",CR,LF
	"write        W [address] [drive] [firstsector] [number]",CR,LF
0105 U 0000 "allocate expanded memory        XA [#pages]",CR,LF
	"deallocate expanded memory      XD [handle]",CR,LF
	"map expanded memory pages       XM [Lpage] [Ppage] [handle]",CR,LF
	"display expanded memory status  XS",CR,LF
EDLIN    00006a34 0035
0006 U 0000 "*"
0007 U 0000 "Invalid drive or file name",CR,LF
0008 U 0000 "File name must be specified",CR,LF
0010 U 0000 "File is READ-ONLY",CR,LF
0011 U 0000 "File Creation Error",CR,LF
0012 U 0000 "Too many files open",CR,LF
0013 U 0000 "Read error in:",CR,LF,"%1",CR,LF
0014 U 0000 "Cannot edit .BAK file--rename file",CR,LF
0015 U 0000 "No room in directory for file",CR,LF
0016 U 0000 "Disk full. Edits lost.",CR,LF
0017 U 0000 "File not found",CR,LF
0018 U 0000 "Entry error",CR,LF
0019 U 0000 "New file",CR,LF
0020 U 0000 "Not found",CR,LF
0021 U 0000 "O.K.? "
0022 U 0000 "Line too long",CR,LF
0023 U 0000 "End of input file",CR,LF
0024 U 0000 "Abort edit (Y/N)? "
0025 U 0000 "Must specify destination line number",CR,LF
0026 U 0000 "Not enough room to merge the entire file",CR,LF
0027 U 0000 CR,LF
0028 U 0000 LF
0029 U 0000 "Continue (Y/N)?"
0030 U 0000 "Unable to print message",CR,LF
0031 U 0000 "%1"
0032 U 0000 "%1:%2"
0033 U 0000 "Cannot merge - code page mismatch",CR,LF
0300 U 0000 "Starts Edlin, a line-oriented text editor.",CR,LF,CR,LF
	"EDLIN [drive:][path]filename [/B]",CR,LF,CR,LF
	"  /B   Ignores end-of-file (CTRL+Z) characters.",CR,LF
0301 U 0000 "Edit line                   line#",CR,LF
	"Append                      [#lines]A",CR,LF
0302 U 0000 "Copy                        [startline],[endline],toline[,times]C",CR,LF
	"Delete                      [startline][,endline]D",CR,LF
0303 U 0000 "End (save file)             E",CR,LF
	"Insert                      [line]I",CR,LF
0304 U 0000 "List                        [startline][,endline]L",CR,LF
	"Move                        [startline],[endline],tolineM",CR,LF
0305 U 0000 "Page                        [startline][,endline]P",CR,LF
	"Quit (throw away changes)   Q",CR,LF
0306 U 0000 "Replace                     [startline][,endline][?]R[oldtext][CTRL+Znewtext]",CR,LF
	"Search                      [startline][,endline][?]Stext",CR,LF
0307 U 0000 "Transfer                    [toline]T[drive:][path]filename",CR,LF
	"Write                       [#lines]W",CR,LF
EXE2BIN  00007278 0012
0002 U 0000 "Insufficient memory",CR,LF
0003 U 0000 "Cannot find messages",CR,LF
0004 U 0000 "Access denied",CR,LF
0005 U 0000 "File cannot be converted",CR,LF
0006 U 0000 "File not found",CR,LF
0007 U 0000 "File creation error",CR,LF
0008 U 0000 "Fix-ups needed - base segment (hex):"
0012 U 0000 "File name must be specified",CR,LF
0300 U 0000 "Converts .EXE (executable) files to binary format.",CR,LF,CR,LF
0301 U 0000 "EXE2BIN [drive1:][path1]input-file [[drive2:][path2]output-file]",CR,LF,CR,LF
0302 U 0000 "  input-file   Specifies the .EXE file to be converted.",CR,LF
0303 U 0000 "  output-file  Specifies the binary file to be created.",CR,LF
GRAPHICS 0000752a 0020
0005 U 0000 "Invalid parameter:  %1",CR,LF
0007 U 0000 "Duplicate parameters not allowed",CR,LF
0009 U 0000 "Cannot find GRAPHICS profile",CR,LF
0010 U 0000 "Required profile statement missing before line %1",CR,LF
0011 U 0000 "Invalid profile statement on line %1",CR,LF
0012 U 0000 "Profile statement out of sequence on line %1",CR,LF
0013 U 0000 "Error reading GRAPHICS profile",CR,LF
0014 U 0000 "Syntax errors in GRAPHICS profile",CR,LF
0015 U 0000 "Printbox ID not in GRAPHICS profile",CR,LF
0016 U 0000 "Printer type not in GRAPHICS profile",CR,LF
0017 U 0000 "/B invalid with a black and white printer",CR,LF
0018 U 0000 "Unable to reload with profile supplied",CR,LF
0300 U 0000 "Loads a program that can print graphics.",CR,LF,CR,LF
0301 U 0000 "GRAPHICS [type] [[drive:][path]filename] [/R] [/B] [/LCD]",CR,LF
	"  [/PRINTBOX:STD | /PRINTBOX:LCD]",CR,LF,CR,LF
0302 U 0000 "  type         Specifies a printer type (see User's Guide and Reference).",CR,LF
0303 U 0000 "  [drive:][path]filename",CR,LF
	"               Specifies the file containing information on supported printers.",CR,LF
0304 U 0000 "  /R           Prints white on black as seen on the screen.",CR,LF
0305 U 0000 "  /B           Prints the background in color for COLOR4 and COLOR8 printers.",CR,LF
0306 U 0000 "  /LCD         Prints using LCD aspect ratio.",CR,LF
0307 U 0000 "  /PRINTBOX:STD | /PRINTBOX:LCD",CR,LF
	"               Specifies the print-box size, either STD or LCD.",CR,LF
KEYB     00007b14 0023
0002 U 0000 "Current keyboard code: %1"
0003 U 0000 "Current keyboard ID: %1"
0004 U 0000 "  code page: %1",CR,LF
0005 U 0000 "Current CON code page: %1",CR,LF
0006 U 0000 "Invalid keyboard code specified",CR,LF
0007 U 0000 "Invalid keyboard ID specified",CR,LF
0008 U 0000 "Invalid code page specified",CR,LF
0009 U 0000 "Bad or missing Keyboard Definition File",CR,LF
0010 U 0000 "KEYB has not been installed",CR,LF
0011 U 0000 "Active code page not available from CON device",CR,LF
0012 U 0000 "Code page specified has not been prepared",CR,LF
0013 U 0000 "One or more CON code pages invalid for given keyboard code",CR,LF
0014 U 0000 "Code page requested (%1) is not valid for given keyboard code",CR,LF
0015 U 0000 "Code page specified is inconsistent with the selected code page",CR,LF
0016 U 0001 "Keyboard ID specified is inconsistent with the selected keyboard layout",CR,LF
0017 U 0000 "Unable to create KEYB table in resident memory",CR,LF
0300 U 0000 "Configures a keyboard for a specific language.",CR,LF,CR,LF
0301 U 0000 "KEYB [xx[,[yyy][,[drive:][path]filename]]] [/E] [/ID:nnn]",CR,LF,CR,LF
0302 U 0000 "  xx                      Specifies a two-letter keyboard code.",CR,LF
0303 U 0000 "  yyy       ÿ             Specifies the code page for the character set.",CR,LF
0304 U 0000 "  [drive:][path]filename  Specifies the keyboard definition file.",CR,LF
0305 U 0000 "  /E                      Specifies that an enhanced keyboard is installed.",CR,LF
0306 U 0000 "  /ID:nnn                 Specifies the keyboard in use.",CR,LF
MEM      0000814b 0113
0010 U 0000  CR,LF
0011 U 0000  "  Segment               Total        Name         Type",CR,LF
0012 U 0000  "  -------          ----------------  -----------  --------",CR,LF
0013 U 0000  "  Handle      EMS Name      Size   ",CR,LF
0014 U 0000  "  -------     --------     ------  ",CR,LF
0015 U 0000  "   %1           %2 %3  %4     %5",CR,LF
0016 U 0000  "                   %1 %2     %3  %4%5",CR,LF
0017 U 0000  "                                        %1  %2",CR,LF
0018 U 0000  "Memory accessible using Int 15h     %1 %2",CR,LF
0019 U 0000  "  "
0020 U 0000  "  XMS version %1; driver version %2",CR,LF
0021 U 0000  "  EMS version %1",CR,LF
0022 U 0000  "LOADHIGH",0
0023 U 0000  "Temporarily Restricted",0
0024 U 0000  "Interrupt Vector",0
0025 U 0000  "ROM Communication Area",0
0026 U 0000  "DOS Communication Area",0
0027 U 0000  "IO",0
0028 U 0000  "MSDOS",0
0029 U 0000  "System Data",0
0030 U 0000  "System Program",0
0031 U 0000  "System Device Driver",0
0032 U 0000  "Installed Device=",0
0033 U 0000  "%1:",0
0034 U 0000  "%1: - %2:",0
0035 U 0000  "BUFFERS=",0
0036 U 0000  "FILES=",0
0037 U 0000  "FCBS=",0
0038 U 0000  "STACKS=",0
0039 U 0000  "DEVICE=",0
0040 U 0000  "IFS=",0
0041 U 0000  "LASTDRIVE=",0
0042 U 0000  "----------",0
0043 U 0000  " ",0
0044 U 0000  "     %1      %2     %3",CR,LF
0045 U 0001  "INSTALL=",0
0046 U 0001  "%1 bytes available contiguous extended memory",CR,LF
0047 U 0000  "System Stacks",0
0048 U 0000  "-- Free --",0
0049 U 0000  "Program",0
0050 U 0000  "Environment",0
0051 U 0000  "Data",0
0052 N 0000  "%1 bytes available XMS memory",CR,LF
0053 U 0000  "The high memory area is available.",CR,LF
0054 U 0000  "The high memory area is not available.",CR,LF
0055 U 0000  "MS-DOS is resident in the high memory area.",CR,LF
0056 U 0000  "IBMBIO",0
0057 U 0000  "IBMDOS",0
0058 U 0000  "MS-DOS is resident in ROM using the high memory area.",CR,LF
0059 U 0000  "Modules using memory below 1 MB:",CR,LF
0060 U 0000  "%1 is using the following memory:",CR,LF
0061 U 0000  "Free Conventional Memory:",CR,LF
0062 U 0000  "Free",0
0063 U 0000  "  Name           Total       =   Conventional   +   Upper Memory",CR,LF
0064 U 0000  "  --------  ----------------   ----------------   ----------------",CR,LF
0065 U 0000  "  Segment        Total",CR,LF
0066 U 0000  "  -------   ----------------",CR,LF
0067 U 0000  "   %1    %2 %3",CR,LF
0068 U 0000  "Too much of memory fragmentation; MEM cannot work properly.",CR,LF
0069 U 0000  "SYSTEM",0
0070 U 0000  "  Total Free:%1 %2",CR,LF
0071 U 0000  "%1 is not currently in memory.",CR,LF
0072 U 0000  "   %1           %2 %3  %4",CR,LF
0073 U 0000  "                   ----------------",CR,LF
0074 U 0000  "  Total Size:      %1 %2",CR,LF
0075 U 0000  "  Segment  Region       Total        Type",CR,LF
0076 U 0000  "  -------  ------  ----------------  --------",CR,LF
0077 U 0000  "   %1     %2   %3 %4  %5",CR,LF
0078 U 0000  "  %1  %2 %3   %4 %5   %6 %7",CR,LF
0079 U 0000  "   %1     %2   %3 %4  %5     %6",CR,LF
0080 U 0000  "Press any key to continue . . ."
0081 U 0000  "No upper memory available",CR,LF
0082 U 0000  "  Segment  Region       Total        Name         Type",CR,LF
0083 U 0000  "  -------  ------  ----------------  -----------  --------",CR,LF
0084 U 0000  "Conventional Memory Detail:",CR,LF
0085 U 0000  "Upper Memory Detail:",CR,LF
0086 U 0000  "Memory Type        Total =  Used  +  Free",CR,LF
0087 U 0000  "----------------  ------   ------   ------",CR,LF
0088 U 0000  "%1  %2   %3   %4",CR,LF
0089 U 0000  "Largest executable program size     %1 %2",CR,LF
0090 U 0000  "Largest free upper memory block     %1 %2",CR,LF
0091 U 0000  "Conventional",0
0092 U 0000  "Upper",0
0093 U 0000  "Extended (XMS)",0
0094 U 0000  "Expanded (EMS)",0
0095 U 0000  "Total memory",0
0096 U 0000  "Total under 1 MB",0
0097 U 0000  "Free Upper Memory:",CR,LF
0098 U 0000  "  Region   Largest Free     Total Free      Total Size",CR,LF
0099 U 0000  "  ------  --------------  --------------  --------------",CR,LF
0100 U 0000  "    %1   %2 %3  %4 %5  %6 %7",CR,LF
0101 U 0000  "Memory Summary:",CR,LF
0102 U 0000  "  Type of Memory          Total       =       Used        +       Free",CR,LF
0103 U 0000  "  ----------------  -----------------   -----------------   -----------------",CR,LF
0104 U 0000  "  %1  %2 %3   %4 %5   %6 %7",CR,LF
0105 U 0000  "Adapter RAM/ROM",0
0106 U 0000  "   %1           %2 %3  %4%5",CR,LF
0107 U 0000  "   %1     %2   %3 %4  %5%6",CR,LF
0108 U 0000  "Total Expanded (EMS)                %1 %2",CR,LF
0109 U 0000  "module name",0
0110 U 0000  "bytes",0
0111 U 0000  "Free Expanded (EMS)                 %1 %2",CR,LF
0112 U 0000  "Extended (XMS)*",0
0113 U 0000  "Free Expanded (EMS)*                %1 %2",CR,LF
0114 U 0000  "* EMM386 is using XMS memory to simulate EMS memory as needed.",CR,LF
0115 U 0000  "  Free EMS memory may change as free XMS memory changes.",CR,LF
0300 U 0000  "Displays the amount of used and free memory in your system.",CR,LF,CR,LF
0301 U 0000  "MEM [/CLASSIFY | /DEBUG | /FREE | /MODULE modulename] [/PAGE]",CR,LF,CR,LF
0302 U 0000  "  /CLASSIFY or /C  Classifies programs by memory usage. Lists the size of",CR,LF
	"                   programs, provides a summary of memory in use, and lists",CR,LF
	"                   largest memory block available.",CR,LF
0303 U 0000  "  /DEBUG or /D     Displays status of programs, internal drivers, and other",CR,LF
	"                   information.",CR,LF
0304 U 0000  "  /FREE or /F      Displays information about the amount of free memory left",CR,LF
	"                   in both conventional and upper memory.",CR,LF
0305 U 0000  "  /MODULE or /M    Displays a detailed listing of a module's memory use.",CR,LF
	"                   This option must be followed by the name of a module,",CR,LF
	"                   optionally separated from /M by a colon.",CR,LF
0306 U 0000  "  /PAGE or /P      Pauses after each screenful of information.",CR,LF
MSBIO    0000991b 0023
0003 U 0000 13,10,"Unrecognized command in CONFIG.SYS"
0004 U 0000 13,10,"$"
0005 U 0000 13,10,"Sector size too large in file $"
0006 U 0000 13,10,"Bad or missing $"
0007 U 0000 "Command Interpreter",0
0008 U 0000 13,10,"Invalid country code or code page",13,10,"$"
0009 U 0000 13,10,"Error in COUNTRY command",13,10,"$"
0010 U 0000 13,10, "Insufficient memory for COUNTRY.SYS file",13,10,"$"
0011 U 0000 13,10,"Configuration too large for memory",13,10,"$"
0012 U 0000 13,10,"Too many block devices",13,10,"$"
0013 U 0000 13,10,"Invalid STACK parameters",13,10,"$"
0014 U 0000 13,10,"Incorrect order in CONFIG.SYS line ","$"
0015 U 0000 "Error in CONFIG.SYS line ","$"
0016 U 0000 13,10,"Memory allocation error ","$"
0017 U 0001 0DH,0AH,7,0DH,0AH, "Internal stack overflow",0DH,0AH
	"System halted",0DH,0AH,"$"
0018 U 0000 "HMA not available : Loading DOS low",13,10,"$"
0019 U 0000 13,10,"failed to boot - missing local driver $"
0020 U 0000 13,10,"Insert diskette for drive "
0021 U 0000 "A: and press any key when ready",13,10,10,0
0022 U 0000 13,10,"Bad command or parameters - $"
0023 U 0000 "Fatal Error:Cannot allocate Memory for DOS", 13, 10, "$"
0024 U 0000 "WARNING! Logical drives past Z: exist and will be ignored",13,10,"$"
0025 U 0000 "This version of DOS will boot only on IBM machines",13,10,0
MSDOS    00009e6b 0007
0001 U 0001 13,10,"Divide overflow",13,10
0002 U 0002 "y"
0003 U 0002 "n"
0004 U 0003 13,10,"A20 Hardware Error",13,10,"$"
0005 U 0000 "Y"
0006 U 0000 "N"
0007 U 0000 "You must have the file WINA20.386 in the root of your boot drive",13,10
	"to run Windows in Enhanced Mode",13,10
NLSFUNC  00009fa4 0003
0300 U 0000 "Loads country-specific information.",CR,LF,CR,LF
0301 U 0000 "NLSFUNC [[drive:][path]filename]",CR,LF,CR,LF
0302 U 0000 "  [drive:][path]filename   Specifies the file containing country-specific",CR,LF
	"                           information.",CR,LF
SHARE    0000a0c8 0005
0003 U 0000 "SHARE cannot be installed under DOSSHELL.",CR,LF
0300 U 0000 "Installs file-sharing and locking capabilities on your hard disk.",CR,LF,CR,LF
0301 U 0000 "SHARE [/F:space] [/L:locks]",CR,LF,CR,LF
0302 U 0000 "  /F:space   Allocates file space (in bytes) for file-sharing information.",CR,LF
0303 U 0000 "  /L:locks   Sets the number of files that can be locked at one time.",CR,LF
SUBST    0000a26e 0010
0002 U 0000 "Incorrect number of parameters",CR,LF
0005 U 0000 "Drive already SUBSTed",CR,LF
0300 U 0000 "Associates a path with a drive letter.",CR,LF,CR,LF
0301 U 0000 "SUBST [drive1: [drive2:]path]",CR,LF
0302 U 0000 "SUBST drive1: /D",CR,LF,CR,LF
0303 U 0000 "  drive1:        Specifies a virtual drive to which you want to assign a path.",CR,LF
0304 U 0000 "  [drive:2]path  Specifies a physical drive and path you want to assign to",CR,LF
0305 U 0000 "                 a virtual drive.",CR,LF
0306 U 0000 "  /D             Deletes a substituted (virtual) drive.",CR,LF,CR,LF
0307 U 0000 "Type SUBST with no parameters to display a list of current virtual drives.",CR,LF
ATTRIB   0000a534 0027
0004 U 0000 "Invalid number of parameters",CR,LF
0005 U 0000 "Invalid path or file not found",CR,LF
0006 U 0000 "Syntax error",CR,LF
0008 U 0000 "  %1"
0009 U 0000 "%1    %2",CR,LF
0010 U 0000 "%1",CR,LF,"%2",CR,LF
0011 U 0000 "%1, Code page mismatch",CR,LF,"Are you sure (Y/N)?"
0012 U 0000 "%1",CR,LF
0014 U 0000 CR,LF
0015 U 0000 "Invalid file type value",CR,LF
0199 U 0000 "Extended attribute error",CR,LF
0201 U 0000 "Extended attribute name not found",CR,LF
0204 U 0000 "Extended attribute name cannot be set",CR,LF
0205 U 0000 "Extended attribute name known to this file system but not supported",CR,LF
0206 U 0000 "Extended attribute type mismatch",CR,LF
0208 U 0000 "Extended attribute value not supported",CR,LF
0216 U 0000 "Not resetting system file %1",CR,LF
0217 U 0000 "Not resetting hidden file %1",CR,LF
0300 U 0000 "Displays or changes file attributes.",CR,LF,CR,LF
0301 U 0000 "ATTRIB [+R | -R] [+A | -A] [+S | -S] [+H | -H] [[drive:][path]filename] [/S]",CR,LF,CR,LF
0302 U 0000 "  +   Sets an attribute.",CR,LF
0303 U 0000 "  -   Clears an attribute.",CR,LF
0304 U 0000 "  R   Read-only file attribute.",CR,LF
0305 U 0000 "  A   Archive file attribute.",CR,LF
0306 U 0000 "  S   System file attribute.",CR,LF
0307 U 0000 "  H   Hidden file attribute.",CR,LF
0308 U 0000 "  /S  Processes files in all directories in the specified path.",CR,LF
ASSIGN   0000aab9 0007
0002 U 0000 "Original %1: set to %2:",CR,LF
0300 U 0000 "Redirects requests for disk operations on one drive to a different drive.",CR,LF,CR,LF
0301 U 0000 "ASSIGN [x[:]=y[:][...]]",CR,LF,"ASSIGN /STATUS",CR,LF,CR,LF
0302 U 0000 "  x        Specifies the drive letter to reassign.",CR,LF
0303 U 0000 "  y        Specifies the drive that x: will be assigned to.",CR,LF
0304 U 0000 "  /STATUS  Displays current drive assignments.",CR,LF,CR,LF
0305 U 0000 "Type ASSIGN without parameters to reset all drive letters to original",CR,LF,"assignments.",CR,LF
CHKDSK   0000ad00 0076
0003 U 0000 "Convert lost chains to files (Y/N)?"
0004 U 0000 "Unrecoverable error in directory"
0005 U 0000 "Convert directory to file (Y/N)?"
0007 U 0000 "%1 bytes total disk space"
0008 U 0000 "%1 bytes in bad sectors"
0009 U 0000 "%1 bytes in %2 hidden files"
0010 U 0000 "%1 bytes in %2 directories"
0011 U 0000 "%1 bytes in %2 user files"
0012 U 0000 "%1 bytes in %2 recovered files"
0013 U 0000 "%1 bytes would be in %2 recovered files"
0014 U 0000 "%1 bytes available on disk"
0015 U 0000 "%1 total bytes memory"
0016 U 0000 "%1 bytes free"
0017 U 0000 "Cannot CHKDSK a network drive"
0018 U 0000 "Cannot CHKDSK a SUBSTed or ASSIGNed drive"
0019 U 0000 "Probable non-DOS disk",CR,LF,"Continue (Y/N)?"
0020 U 0000 "Disk error reading FAT %1",CR,LF
0021 U 0000 "Directory %1"
0022 U 0000 "%1 Contains %2 non-contiguous blocks"
0023 U 0000 "All specified file(s) are contiguous"
0024 U 0000 "Errors found, F parameter not specified",CR,LF,"Corrections will not be written to disk"
0025 U 0000 "   Processing cannot continue %1%2"
0026 U 0000 "   File allocation table bad, drive %1"
0029 U 0000 "   CHDIR .. failed, trying alternate method"
0030 U 0001 "   Has invalid allocation unit, file truncated"
0031 U 0000 "   Invalid sub-directory entry"
0032 U 0000 "   Does not exist"
0033 U 0001 "   First allocation unit is invalid, entry truncated"
0034 U 0000 "   Allocation error, size adjusted"
0035 U 0000 "   Cannot recover .. entry, processing continued"
0036 U 0000 "   Directory is totally empty, no . or .."
0037 U 0000 "   Directory is joined"
0038 U 0000 "   Cannot recover .. entry"
0039 U 0000 "   Entry has a bad link"
0040 U 0000 "   Entry has a bad attribute"
0041 U 0000 "   Entry has a bad size"
0042 U 0001 "   Is cross linked on allocation unit %1"
0043 U 0000 "   Cannot CHDIR to %1,",CR,LF,"tree past this point not processed"
0044 U 0000 "   tree past this point not processed"
0045 U 0000 "%1 bytes disk space freed"
0046 U 0000 "%1 bytes disk space would be freed"
0047 U 0000 "Volume %1 created %2 %3",CR,LF
0048 U 0000 "%1 total allocation units on disk"
0049 U 0000 "%1 bytes in each allocation unit"
0050 U 0000 "CHKDSK not available on drive %1"
0051 U 0001 "   Extended Attributes has invalid allocation units, attributes truncated"
0052 U 0000 "   Extended Attributes allocation error , attributes truncated"
0053 U 0000 "Invalid parameter"
0055 U 0000 "Path not found"
0056 U 0000 "File not found"
0058 U 0001 "   %1 lost allocation units found in %2 chains."
0059 U 0000 CR,LF
0060 U 0000 "   Cannot CHDIR to root",CR,LF
0061 U 0000 "   Disk error writing FAT %1"
0062 U 0000 "        %1"
0063 U 0000 "Invalid current directory"
0064 U 0000 "%1",CR,LF
0065 U 0000 "   Insufficient room in root directory",CR,LF,"   Move files from root directory and repeat CHKDSK"
0066 U 0000 "%1 %2 %3"
0067 U 0000 "%1 %2, %3"
0068 U 0000 "%1%2%3%4%5"
0069 U 0000 "%1%2%3%4"
0070 U 0000 "%1 available allocation units on disk"
0075 U 0000 "Quit Windows and try again"
0076 U 0000 " - Insufficient Memory"
0077 U 0000 "File allocation table bad"
0078 U 0000 "CHKDSK cannot check the validity of this drive..."
0079 U 0000 "%1"
0080 U 0000 "To run CHKDSK, the drive must not contain..."
0300 U 0000 "Checks a disk and displays a status report.",CR,LF,CR,LF
0301 U 0000 "CHKDSK [drive:][[path]filename] [/F] [/V]",CR,LF,CR,LF
0302 U 0000 "  [drive:][path]  Specifies the drive and directory to check.",CR,LF
0303 U 0000 "  filename        Specifies the file(s) to check for fragmentation.",CR,LF
0304 U 0000 "  /F              Fixes errors on the disk.",CR,LF
0305 U 0000 "  /V              Displays the full path and name of every file on the disk.",CR,LF,CR,LF
0306 U 0000 "Type CHKDSK without parameters to check the current disk.",CR,LF
XCOPY    0000bc13 0032
0004 U 0000 "Does %1 specify a file name",CR,LF
	"or directory name on the target",CR,LF
	"(F = file, D = directory)?"
0005 U 0000 "Press any key to begin copying file(s)"
0006 U 0000 "Path too long",CR,LF
0008 U 0000 "Cannot perform a cyclic copy",CR,LF
0012 U 0000 "Cannot XCOPY from a reserved device",CR,LF
0021 U 0000 "Invalid number of parameters",CR,LF
0022 U 0000 "Cannot XCOPY to a reserved device",CR,LF
0024 U 0000 "File creation error",CR,LF
0025 U 0000 "Reading source file(s)...",CR,LF
0026 U 0000 CR,LF
0027 U 0000 "%1 File(s) copied",CR,LF
0029 U 0000 "F D "
0030 U 0000 "%1%2",CR,LF
0031 U 0000 "%1\%2",CR,LF
0032 U 0000 "%1",CR,LF
0033 U 0000 "%1%2 (Y/N)?"
0034 U 0000 "%1\%2 (Y/N)?"
0036 U 0000 "Invalid Path, not all directories/files copied",CR,LF
0300 U 0000 "Copies files (except hidden and system files) and directory trees.",CR,LF,CR,LF
0301 U 0000 "XCOPY source [destination] [/A | /M] [/D:date] [/P] [/S [/E]] [/V] [/W]",CR,LF,CR,LF
0302 U 0000 "  source       Specifies the file(s) to copy.",CR,LF
0303 U 0000 "  destination  Specifies the location and/or name of new files.",CR,LF
0304 U 0000 "  /A           Copies files with the archive attribute set,",CR,LF
0305 U 0000 "               doesn't change the attribute.",CR,LF
0306 U 0000 "  /M           Copies files with the archive attribute set,",CR,LF
0307 U 0000 "               turns off the archive attribute.",CR,LF
0308 U 0000 "  /D:date      Copies files changed on or after the specified date.",CR,LF
0309 U 0000 "  /P           Prompts you before creating each destination file.",CR,LF
0310 U 0000 "  /S           Copies directories and subdirectories except empty ones.",CR,LF
0311 U 0000 "  /E           Copies any subdirectories, even if empty.",CR,LF
0312 U 0000 "  /V           Verifies each new file.",CR,LF
0313 U 0000 "  /W           Prompts you to press a key before copying.",CR,LF
SYS      0000c3a8 0016
0007 U 0000 "No room for system on destination disk",CR,LF
0008 U 0001 "Incompatible system size",CR,LF
0010 U 0000 "No system on default drive",CR,LF
0011 U 0000 "Can not specify default drive",CR,LF
0012 U 0000 "Write failure, diskette unusable",CR,LF 
0014 U 0000 "Insert system disk in drive %1",CR,LF 
0016 U 0000 "Not able to SYS to %1 file system",CR,LF
0018 U 0000 "Source path and target drive cannot be the same"
0020 U 0000 "Error reading system files from source",CR,LF
0021 U 0000 "SYS can not operate on target drive",CR,LF
0025 U 0000 CR,LF,"Could not copy COMMAND.COM onto target disk",CR,LF
0026 U 0000 "Insufficient memory",CR,LF
0300 U 0000 "Copies MS-DOS system files and command interperter to a disk you specify.",CR,LF,CR,LF
0301 U 0000 "SYS [drive1:][path] drive2:",CR,LF,CR,LF
0302 U 0000 "  [drive1:][path] Specifies the location of the system files.",CR,LF
0303 U 0000 "  drive2:         Specifies the drive the files are to be coppied to.",CR,LF
MORE     0000c79e 0007
0002 U 0000 "-- More --"
0003 U 0000 "Too many arguments in command line"
0300 U 0000 "Displays output one screen at a time.",CR,LF,CR,LF
0301 U 0000 "MORE < [drive:][path]filename",CR,LF
0302 U 0000 "command-name | MORE",CR,LF,CR,LF
0303 U 0000 "  [drive:][path]filename  Specifies a file to display one screen at a time.",CR,LF
0304 U 0000 "  command-name            Specifies a command whose output will be displayed.",CR,LF
MODE     0000c969 0079
0003 U 0000 CR,LF,"Must specify COM1, COM2, COM3 or COM4",CR,LF
0004 U 0000 CR,LF,"Resident portion of MODE loaded",CR,LF
0005 U 0000 CR,LF,"Illegal device name",CR,LF
0006 U 0000 CR,LF,"Printer error",CR,LF
0007 U 0000 CR,LF,"LPT%1: set for 80",CR,LF
0008 U 0000 CR,LF,"LPT%1: set for 132",CR,LF
0009 U 0000 CR,LF,"Printer lines per inch set",CR,LF
0010 U 0000 CR,LF,"Invalid baud rate specified",CR,LF
0011 U 0000 CR,LF,"COM%1: %2,%3,%4,%5,%6",CR,LF
0012 U 0000 "0123456789"
0013 U 0001 CR,LF,"Do you see the %1? (Y/N) "
0015 U 0000 "LPT%1: rerouted to COM%2:",CR,LF
0016 U 0000 "LPT%1: not rerouted",CR,LF
0017 U 0000 CR,LF,"%1 retry on parallel printer time-out",CR,LF
0018 U 0000 CR,LF,"      Unable to shift screen %1",CR,LF
0020 U 0000 CR,LF,"Invalid number of parameters",CR,LF
0021 U 0000 CR,LF,"NET 042: Unable to do requested command",CR,LF
0022 U 0001 CR,LF,"Infinite retry not supported on network printer",CR,LF
0023 U 0001 CR,LF,"Failure to access code page font file",cr,lf
0024 U 0000 CR,LF,"Failure to access device: %1",CR,LF
0025 U 0001 CR,LF,"Device or code page missing from font file",CR,LF
0026 U 0000 CR,LF,"Font file contents invalid",CR,LF
0027 U 0001 CR,LF,"Previously prepared code page replaced",CR,LF
0028 U 0001 CR,LF,"Active code page for device %1 is %2",CR,LF
0029 U 0000 CR,LF,"Device %1 not prepared",CR,LF
0030 U 0001 "%1 code pages:",CR,LF
0031 U 0001 "  code page %1",CR,LF
0032 U 0001 CR,LF,"MODE %1 code page function completed",CR,LF
0033 U 0002 CR,LF,"Current code page settings:",CR,LF
0034 U 0002 "   %1 - %2 code page",CR,LF
0035 U 0002 "  code page not prepared",CR,LF
0036 U 0002 "Code page operation not supported on this device",CR,LF
0037 U 0002 "No code page has been selected",cr,lf
0038 U 0002 "Device error during %1",CR,LF
0039 U 0002 "Code page not prepared",CR,LF
0040 U 0002 CR,LF,"Current keyboard does not support this code page",CR,LF
0041 U 0002 CR,LF,"Error during read of font file",CR,LF
0042 U 0002 CR,LF,"Unable to perform refresh operation",CR,LF
0043 U 0002 CR,LF
0044 U 0002 CR,LF,"Status for device %1:",CR,LF
0045 U 0002 "------------------"
0046 U 0002 "----",CR,LF
0047 U 0002 "-----",CR,LF
0048 U 0002 "LINES=%1",CR,LF
0049 U 0002 "COLUMNS=%1",CR,LF
0050 U 0002 CR,LF,"RATE and DELAY must be specified together",CR,LF
0051 U 0002 "RATE=%1",CR,LF
0052 U 0002 "DELAY=%1",CR,LF
0053 U 0002 CR,LF,"Function not supported on this computer - %1",CR,LF
0054 U 0002 CR,LF,"Required font not loaded",CR,LF
0055 U 0002 CR,LF,"ANSI.SYS must be installed to perform requested function",CR,LF
0056 U 0002 CR,LF,"Baud rate required",CR,LF
0057 U 0002 "RETRY=%1",CR,LF
0059 U 0002 "rightmost 9",0
0060 U 0002 "leftmost 0",0
0061 U 0002 "No",0
0062 U 0002 "Infinite",0
0063 U 0002 "left",0
0064 U 0002 "right",0
0065 U 0002 "Hardware",0
0066 U 0002 "Prepared",0
0067 U 0002 "status",0
0068 U 0002 "prepare",0
0069 U 0002 "select",0
0070 U 0002 "refresh",0
0071 U 0002 "write of font file to device",0
0072 U 0002 "selected",0
0073 U 0002 "system",0
0300 U 0000 "Configures system devices.",CR,LF,CR,LF
0301 U 0000 "Printer port:      MODE LPTn[:] [COLS=c] [LINES=l] [RETRY=r]",CR,LF
0302 U 0000 "Serial port:       MODE COMm[:] [BAUD=b] [PARITY=p] [DATA=d] [STOP=s] [RETRY=r]",CR,LF
0303 U 0000 "Device Status:     MODE [device] [/STATUS]",CR,LF
0304 U 0000 "Redirect printing: MODE LPTn[:]=COMm[:]",CR,LF
0305 U 0000 "Prepare code page: MODE device CP PREPARE=((yyy[...]) [drive:][path]filename)",CR,LF
0306 U 0000 "Select code page:  MODE device CP SELECT=yyy",CR,LF
0307 U 0000 "Refresh code page: MODE device CP REFRESH",CR,LF
0308 U 0000 "Code page status:  MODE device CP [/STATUS]",CR,LF
0309 U 0000 "Display mode:      MODE [display-adapter][,n]",CR,LF
	"                   MODE CON[:] [COLS=c] [LINES=n]",CR,LF
0310 U 0000 "Typematic rate:    MODE CON[:] [RATE=r DELAY=d]",CR,LF
DISKCOPY 0000d8da 0026
0002 U 0000 CR,LF
0004 U 0000 "Do not specify filename(s)",CR,LF
	"Command Format: DISKCOPY [drive1: [drive2:]] [/1] [/V]",CR,LF
0005 U 0000 CR,LF,"Invalid drive specification",CR,LF
	"Specified drive does not exist",CR,LF
	"or is non-removable",CR,LF
0006 U 0000 CR,LF,"Cannot DISKCOPY to or from",CR,LF
	"a network drive",CR,LF
0007 U 0000 CR,LF,"Formatting while copying",CR,LF
0008 U 0000 CR,LF,"Insert SOURCE diskette in drive %1:",CR,LF
0009 U 0000 CR,LF,"Insert TARGET diskette in drive %1:",CR,LF
0010 U 0000 "Make sure a diskette is inserted into",CR,LF
	"the drive and the door is closed",CR,LF
0011 U 0000 CR,LF,"Target diskette may be unusable",CR,LF
0012 U 0000 CR,LF,"Target diskette unusable",CR,LF
0016 U 0000 CR,LF,"Copy another diskette (Y/N)? "
0017 U 0000 CR,LF,"Copying %1 tracks",CR,LF
	"%2 Sectors per Track, %3 Side(s)",CR,LF
0018 U 0000 CR,LF,"Drive types or diskette types",CR,LF
	"not compatible",CR,LF
0019 U 0000 CR,LF,"Unrecoverable read error on drive %1",CR,LF
	"Side %2, track %3",CR,LF
0020 U 0000 CR,LF,"Unrecoverable write error on drive %1",CR,LF
	"Side %2, track %3",CR,LF
0021 U 0000 CR,LF,"Copy process ended",CR,LF
0022 U 0000 CR,LF,"SOURCE diskette bad or incompatible"
0023 U 0000 CR,LF,"TARGET diskette bad or incompatible"
0030 U 0000 CR,LF,"TARGET media has lower capacity than SOURCE",CR,LF,"Continue anyway (Y/N)?"
0031 U 0000 CR,LF,"Press CTRL+C to abort,",CR,LF,"or correct this problem and press any other key to continue . . .",CR,LF
0300 U 0000 "Copies the contents of one floppy disk to another.",CR,LF,CR,LF
0301 U 0000 "DISKCOPY [drive1: [drive2:]] [/1] [/V]",CR,LF,CR,LF
0302 U 0000 "  /1   Copies only the first side of the disk.",CR,LF
0303 U 0000 "  /V   Verifies that the information is copied correctly.",CR,LF,CR,LF
0304 U 0000 "The two floppy disks must be the same type.",CR,LF,"You may specify the same drive for drive1 and drive2.",CR,LF
0032 U 0000 CR,LF,"DISKCOPY cannot copy memory card (CMCDD) devices.",CR,LF
