;
;	Microsoft Confidential
;	Copyright (C) Microsoft Corporation 1991
;	All Rights Reserved.
;

; DOS OEM number assignments.
; This file is for documentation purposes only.  It lists the currently
; assigned OEM numbers, for use with the DOS GetVersion call.
;
; IBM DOS             (00)
; Compaq DOS          (01)
; MS Packaged Product (02)
; AT&T DOS            (04)
; Zenith DOS          (05)
; HP DOS              (06)
; Zenith DOS for DOS 5.0 and later      (07)
; Tandon              (08)
; AST                 (09)
; Asem                (10)
; Hantarex            (11)
; SystemsLine         (12)
; Packard Bell        (13)
; Intercomp           (14)
; Unibit              (15)
; Unidata             (16)
; Olivetti DOS        (23)
; Undefined           (255)  
