01: 07,"An incompatible DOSKey is already installed.$"

02: 07,"Cannot change BUFSIZE.$"

03: "DOSKey installed.$"

04: "Invalid macro definition.$"

05: "Edits command lines, recalls MS-DOS commands, and creates macros.",13,10,13,10
"DOSKEY [/REINSTALL] [/BUFSIZE=size] [/MACROS] [/HISTORY]",13,10
"  [/INSERT | /OVERSTRIKE] [macroname=[text]]",13,10,13,10
"  /REINSTALL    Installs a new copy of Doskey.",13,10
"  /BUFSIZE=size Sets size of command history buffer.",13,10
"  /MACROS       Displays all Doskey macros.",13,10
"  /HISTORY      Displays all commands stored in memory.",13,10
"  /INSERT       Specifies that new text you type is inserted in old text.",13,10
"  /OVERSTRIKE   Specifies that new text overwrites old text.",13,10
"  macroname     Specifies a name for a macro you create.",13,10
"  text          Specifies commands you want to record.",13,10,13,10
"UP and DOWN ARROWS recall commands; ESC clears command line; F7 displays",13,10
"command history; ALT+F7 clears command history; F8 searches command",13,10
"history; F9 selects a command by number; ALT+F10 clears macro definitions.",13,10,13,10
"The following are some special codes in Doskey macro definitions:",13,10
"$T     Command separator.  Allows multiple commands in a macro.",13,10
"$1-$9  Batch parameters.  Equivalent to %1-%9 in batch programs.",13,10
"$*     Symbol replaced by everything following macro name on command line.",13,10,0

06: 07,"Insufficent memory to store macro. Use the DOSKEY command with the /BUFSIZE",13,10,"switch to increase available memory.$",0

07: 07,"Incorrect DOS version$"

08: 13,10,"$"

20: 13,10,"-- More --",0

21: "Line number: ",0
