20: 13,10,"Insert diskette for drive "

21: "A: and press any key when ready",13,10,10,0

17: 13,10,7,13,10,"Internal stack overflow",13,10,"System halted",13,10,"$"

18: "HMA not available: Loading DOS low", 13, 10, "$"

23: "Fatal Error: Cannot allocate Memory for DOS", 13, 10, "$"

43: "Wrong DBLSPACE.BIN version",13,10,"$"

03: 13,10,"Unrecognized command in CONFIG.SYS"

11: 13,10,"Configuration too large for memory",13,10,"$"

10: 13,10,"Insufficient memory for COUNTRY.SYS file",13,10,"$"

14: 13,10,"Incorrect order in CONFIG.SYS line ","$"

22: 13,10,"Bad command or parameters - $"

29: "ONOFF"

34: 13,10,"  MS-DOS 6 Startup Menu",13,10,"  อออออออออออออออออออออ",13,10,"$"

41: "Enter correct name of Command Interpreter (eg, C:\COMMAND.COM)",13,10,"$"

24: "WARNING! Logical drives past Z: exist and will be ignored",13,10,"$"

04: 13,10,'$'

12: 13,10,"Too many block devices",13,10,"$"

08: 13,10,"Invalid country code or code page",13,10,"$"

15: "Error in CONFIG.SYS line ","$"

30: "Starting MS-DOS...",13,10,10,0

35: "  Enter a choice: $"

42: "Process AUTOEXEC.BAT [Y,N]?$"

05: 13,10,"Sector size too large in file $"

13: 13,10,"Invalid STACK parameters",13,10,"$"

09: 13,10,"Error in COUNTRY command",13,10,"$"

31: "Press any key to continue . . .",13,10,"$"

36: "  F5=Bypass startup files    F8=Confirm each CONFIG.SYS line [ ]$"

06: 13,10,"Bad or missing $"

32: "MS-DOS is bypassing your CONFIG.SYS and AUTOEXEC.BAT files.",13,10,"$"

37: " [Y,N]?$"

07: "Command Interpreter",0

33: "MS-DOS will prompt you to confirm each CONFIG.SYS command.",13,10,"$"

38: "YES$"

39: "NO $"

40: "Time remaining: $"

16: 13,10,"Memory allocation error ","$"

25: "This version of DOS will boot only on IBM machines",13,10,0

19: 13,10,"failed to boot - missing local driver $"
