; Copyright 1990 Central Point Software, Inc.
; All rights reserved.
;-----------------------------------------------------------------------------
; Modified April 19, 1988.  Removed dumb 'stand_alone' stuff.  GWD.
; Modified main warning msg to recommend DISKFIX.  6.0 BETA 02-14-90  GWD.
; Tiny changes for easier translation.  v6 03-05-90  GWD.
;
; These are the messages for Jim's half of REBUILD.COM
; They are now in the form of an INCLUDE-file (not public/externals).
;
; All of the messages in Jim's stuff are displayed using DOS fct #9.
; The dollar signs ($) mark the end of strings.
;
;       M000    MD      9/23/90         Cleaned up signon message
;       M001    MD     10/14/90         More message cleanup 
;
;-----------------------------------------------------------------------------
; These symbols define the single character responses to the questions.
; Make sure these match the text of the prompts.
;
yes_char	EQU	"Y"	;Answer is Yes.
no_char		EQU	"N"	;Answer is No.
prior_char	EQU	"P"	;Answer is use the Prior file.
last_char	EQU	"L"	;Answer is use the Last (later) file.
;
abort_char	EQU	"A"	;Answer is Abort after the error.
retry_char	EQU	"R"	;Answer is Retry (try the operation again).
ignore_char	EQU	"I"	;Answer is Ignore the error.
;
;-----------------------------------------------------------------------------
; These messages can be generated by typing the command REBUILD and pressing
; enter.  Since no drive was specified the command is aborted.
;
;

REBUILD_MAIN_MSG LABEL byte

;	DB    "Unauthorized duplication prohibited."    M000
;	DB    13,10                                     M000

  		DB  13,10,"Restores the system area of your disk by using the image file created"
; The text in this line cannot exceed 80 chars in length

		  DB  13,10,"by the MIRROR command.",13,10
; The text in this line cannot exceed 80 chars in length


  DB	13,10
  DB	"    WARNING !!        WARNING !!"
  DB	13,10
  DB	13,10
  DB	"This command should be used only to recover from the inadvertent use of"
  DB	13,10
  DB	"the FORMAT command or the RECOVER command.  Any other use of the UNFORMAT"
  DB	13,10
  DB	"command may cause you to lose data!  Files modified since the MIRROR image"
  DB	13,10
  DB	"file was created may be lost."
  db	13,10,13,10				; M003
  db	"Searching disk for MIRROR image."	; M003
;;   Every one of the above lines must be less than 80 characters long.

;M001 - some text deleted above

	COMMENT @
;  **  All the following lines are ignored, up to the next 'At-sign'.
		  DB  13,10,'  WARNING !!'
		  DB  13,10,'REBUILD SHOULD ONLY BE USED TO RECOVER FROM THE'
		  DB  13,10,'INADVERTENT USE OF THE DOS FORMAT COMMAND OR'
		  DB  13,10,'THE DOS RECOVER COMMAND. ANY OTHER USE OF REBUILD'
		  DB  13,10,'MAY CAUSE YOU TO LOSE DATA! ANY MODIFICATIONS'
		  DB  13,10,'MADE SINCE THE LAST USE OF MIRROR MAY BE LOST.'
	COMMENT @ END



		  DB  13,10,"$"
; This line cannot be changed



PROBLEMS  DB   13,10,"UNFORMAT aborted."
; The text in this line cannot exceed 80 chars in length

LINE_DOWN DB   13,10,"$"

;-----------------------------------------------------------------------------
; This messages can be generated by inserting a DOS formatted diskette that
; was not used with MIRROR.  Type REBUILD A: and press enter. Takes about
; 45 seconds.


NO_FILE  DB    13,10,"MIRROR image file not found.",13,10,"$"
; The text in this line cannot exceed 80 chars in length

;------------------------------------------------------------------------------
; This message is generated if you are using a version of DOS less than 2.0


BAD_VERSION DB 13,10,"Need DOS version 2.x or higher",13,10,"$"
; The text in this line cannot exceed 80 chars

;------------------------------------------------------------------------------
; This message is generated if IBM PC-NET is installed and you try to run the
; REBUILD program.

; This message is no longer needed.  Glen's module checks it & reports.  v5.5
;* NETWORK_INSTALLED DB 13,10,'Network installed. UNFORMAT must'
; The text in this line cannot exceed 80 chars
;
; *		  DB 13,10,'be run without the network.',13,10,7,'$'
; The text in this line cannot exceed 80 chars

;------------------------------------------------------------------------------
; If you install Mirror on a drive that does not exist, this message will be
; generated.

DRIVE_MSG DB 13,10,"Drive "
drive_msg_patch	DB "x ","$"


DRIVE_SPEC_ERROR DB "could not be processed.",13,10,"$"
; This text in this message cannot exceed 71 chars in length
;

;------------------------------------------------------------------------------
; If you insert a diskette with a bad sector into the A: drive and run the
; REBUILD A: program, this message will be generated.


BAD_SECTOR_MSG DB 13,10,"Bad sector being bypassed.",13,10,"$"
; The text in this message cannot exceed 80 chars in length

;------------------------------------------------------------------------------
; This message can be issued by editing the mirror file MIRORSAV.FIL and
; adding bad information.


BAD_FILE DB    13,10,"The MIRROR image file found has inconsistent"
; The text in this message cannot exceed 80 chars

	 DB    13,10,"information. It cannot be used.",13,10,"$"
; The text in this message cannot exceed 80 chars

;------------------------------------------------------------------------------
; If you terminate the REBUILD process this message will be generated.


USER_CANCELLED DB 13,10,"Cancelled by user.",13,10,"$"
; The text in this message cannot exceed 80 chars in length

;-------------------------------------------------------------------------------
; If REBUILD is executed on a diskette that has a valid Mirror file , these
; messages will be generated.


LOOKS_GOOD   DB 13,10,"The MIRROR image file has been validated.",13,10,"$"
; The text in this messages cannot exceed 80 chars in length




LAST_MSG    DB 13,10,"The last$"
PRIOR_MSG   DB "The prior$"
DATE_MSG    DB " time the MIRROR or FORMAT command was used was at "
;
; The following item will be patched at run-time with the time text.
; The ':' may be replaced by another character.  Leave the XX's unchanged.
TIME_MSG    DB "XX:XX"
	    DB " on "
MODAY_MSG   DB "MM/DD/YY."  ;Date is patched at run-time for current country.
	    DB 13,10,"$"
; The total text length of these messages cannot exceed 80 chars



WANNA_CONT  DB 13,10,"Are you sure you want to update the system area of your drive "
; This message cannot exceed 80 chars in length.

WANNA_DRIVE DB "x "		; This line cannot be changed.
	    DB "(Y/N)? "
	    DB "$"


JUST_CHECKING_MSG DB 10,13,'Just checking this time.  No changes written to disk.'
		  DB 10,13,'$'                        


SUCC	   DB  13,10,"The system area of drive "
SUCC_DRIVE DB  "x has been rebuilt.",13,10
; The text in the above two lines cannot exceed 80 chars in length

	   DB  13,10,"You may need to restart the system.",13,10,"$"
; This text in this message cannot exceed 80 chars in length


SUCC_ALT   DB	 13,10,"The system area of drive "
SUCC_ALT_D DB  "x "
	   DB  "has been verified"
; The total length of the text in the above two lines cannot exceed 80
; chars in length, the first char of SUCC_ALT_D cannot be changed

	   DB	 13,10,"to agree with the MIRROR image file.",13,10,"$"
; The text in this line cannot exceed 80 chars in length



FAILED_CHK DB 13,10,"The system area does not agree with the"
; The length of the text in this line cannot exceed 80 chars in length

	   DB 13,10,"MIRROR image file.",13,10,"$"
; The length of the text in this line cannot exceed 80 chars in length

;------------------------------------------------------------------------------
; This message is generated by running Mirror twice on the same drive.	You
; will then get a Last and a Prior Mirror file to choose from.


WITCH_MSG DB   13,10,"If you wish to use the last file as indicated"
; This text in this message cannot exceed 80 chars in length

	  DB   13,10,"above, press L. If you wish to use the prior"
; This text in this message cannot exceed 80 chars in length

	  DB   13,10,"file as indicated above, press P. Press ESC"
; This text in this message cannot exceed 80 chars in length

	  DB   13,10,"to cancel UNFORMAT.",13,10,"$"
; This text in this message cannot exceed 80 chars in length

;------------------------------------------------------------------------------
; This message is generated when the Mirror control files cannot be found when
; you are doing the REBUILD C: operation.


CANT_FIND_MIRROR_MSG  DB 13,10,"Unable to find the MIRROR"
; This text in this message cannot exceed 80 chars in length

	 DB       " control file. If you want to search for the"
; This text in this message cannot exceed 80 chars in length

	 DB 13,10,"MIRROR image file through the entire hard drive,"
; This text in this message cannot exceed 80 chars in length

	 DB 13,10,"press Y, or press N to cancel the UNFORMAT command.",13,10,"$"
; This text in this message cannot exceed 80 chars in length

;------------------------------------------------------------------------------
; If an error occurs during the reading or writing of sectors these messages
; will be generated.


ERROR_READ DB 13,10,"Error reading logical sector ","$"
; This text in this message cannot exceed 80 chars in length



ERROR_WRITE DB 13,10,"Error writing logical sector ","$"
; This text in this message cannot exceed 80 chars in length
;------------------------------------------------------------------------------

;------------------------------------------------------------------------------
; This message occurs after a severe error, you will be asked if you want to
; abort, retry, or ignore.
;
; Make sure the symbols for the response letters match this text.

H_E_QUESTION DB 13,10,"A=Abort, R=Retry, I=Ignore",13,10,"$"
; The text in this message cannot exceed 80 chars in length

;------------------------------------------------------------------------------
; These messages are generated when there are no mirror control files to use
; and the search of the hard drive is being performed.


HARD_WAY_MSG DB 13,10,"A suspected MIRROR file starting at sector "
HARD_WAY_NUM DB "xxxxxxx "		;Do not change this line.
	     DB "has been found.$"
; The total text for these two lines cannot exceed 80 chars in length



HARD_WAY_BACKUP_BAD DB 13,10,"The suspected MIRROR file is invalid. Continuing search.",13,10,"$"
; The text for this message cannot exceed 80 chars in length


HARD_WAY_BACKUP_MSG DB 13,10,"The file is a backup to a more recent MIRROR image file.$"
; The text for this message cannot exceed 80 chars in length


HARD_WAY_ASK_MSG DB 10,13,10,"Do you want to use this file for unformatting or continue searching?"
; The text for this message cannot exceed 80 chars in length

		 DB 13,10,"Press Y to use this file, or N to keep searching.",13,10,"$"
; The text for this message cannot exceed 80 chars in length
;
;------------------  End of Jim's messages include-file  --------------------
;
