	PAGE	90,132			;A2
	TITLE	GRTABEE - LATIN 2 CHARACTER SET
;/*
; *                      Microsoft Confidential
; *                      Copyright (C) Microsoft Corporation 1981 - 1991
; *                      All Rights Reserved.
; */

;This module is to be linked with the OBJ of GRTAB.ASM.  Refer to the
;Prolog of that module for more complete description.

;This module contains the binary description of the pixels that are used
;in graphics mode to define the multi-lingual character set when loaded to
;interrupt 1FH by the GRAFTABL command in DOS 3.3.
	IF1
	    %OUT    GRTABEE.ASM...
	ELSE
;    %OUT GRTABEE.ASM...
	ENDIF
CSEG	SEGMENT PARA PUBLIC
TABLEEE EQU	THIS BYTE
	PUBLIC	TABLEEE

;(note: the display of the character to the right of the decimal number
;value of this location is not necessarily the graphic that these pixels
;will produce.	The displayed character is from the USA character set, and
;does not represent the language character set generated by this table.)

;These fonts are as defined in the LATIN 2 Code Page = 852.

;       *** HEX 80 ***
        DB      00111100B    ;128 Ä  C sedilla
        DB      01100110B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      01100110B
        DB      00111100B
        DB      00001100B
;
;       *** HEX 81 ***
        DB      11001100B   ;129 Å
        DB      00000000B
        DB      11001100B
        DB      11001100B
        DB      11001100B
        DB      11001100B
        DB      01110110B
        DB      00000000B
;
;       *** HEX 82 ***
        DB      00011100B    ;130 Ç
        DB      00000000B
        DB      01111000B
        DB      11001100B
        DB      11111100B
        DB      11000000B
        DB      01111000B
        DB      00000000B
;
;       *** HEX 83 ***
        DB      01111000B    ;131 É
        DB      10000100B
        DB      01111000B
        DB      00001100B
        DB      01111100B
        DB      11001100B
        DB      01110110B
        DB      00000000B
;
;       *** HEX 84 ***
        DB      11001100B    ;132 Ñ
        DB      00000000B
        DB      01111000B
        DB      00001100B
        DB      01111100B
        DB      11001100B
        DB      01111110B
        DB      00000000B
;
;       *** HEX 85 ***       chnaged
        DB      00110000B    ;133 u circle
        DB      11001100B
        DB      00110000B
        DB      11001100B
        DB      11001100B
        DB      11001100B
        DB      01110110B
        DB      00000000B
;
;       *** HEX 86 ***       changed
        DB      00001100B    ;134 c acute
        DB      00110000B
        DB      00111100B
        DB      11000110B
        DB      11000000B
        DB      11000110B
        DB      00111100B
        DB      00000000B
;
;       *** HEX 87 ***
        DB      00000000B    ;135 á
        DB      00000000B
        DB      01111000B
        DB      11001100B
        DB      11000000B
        DB      11001100B
        DB      01111000B
        DB      00011000B
;
;       *** HEX 88 ***       changed
        DB      00110000B    ;136 l slash
        DB      00110110B
        DB      00111100B
        DB      00111000B
        DB      00110000B
        DB      01110000B
        DB      11011100B
        DB      00000000B
;
;       *** HEX 89 ***
        DB      11001100B    ;137 â
        DB      00000000B
        DB      01111000B
        DB      11001100B
        DB      11111100B
        DB      11000000B
        DB      01111000B
        DB      00000000B
;
;       *** HEX 8A ***       changed
        DB      11101110B    ;138 O double acute
        DB      10001000B
        DB      01111100B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX 8B ***       changed
        DB      11101110B    ;139 o with double acute
        DB      10001000B
        DB      01111000B
        DB      11001100B
        DB      11001100B
        DB      11001100B
        DB      01111000B
        DB      00000000B
;
;       *** HEX 8C ***
        DB      01110000B   ;140 å
        DB      10001000B
        DB      01110000B
        DB      00110000B
        DB      00110000B
        DB      00110000B
        DB      01111000B
        DB      00000000B
;
;       *** HEX 8D ***      changed
        DB      00011100B   ;141 Z acute
        DB      00010000B
        DB      11111110B
        DB      00001100B
        DB      00110000B
        DB      01100000B
        DB      11111110B
        DB      00000000B
;
;       *** HEX 8E ***
        DB      11000110B   ;142 é
        DB      00111000B
        DB      01101100B
        DB      11000110B
        DB      11111110B
        DB      11000110B
        DB      11000110B
        DB      00000000B
;
;       *** HEX 8F ***      changed
        DB      00011100B   ;143 C acute
        DB      00010000B
        DB      01111100B
        DB      11000110B
        DB      11000000B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX 90 ***      changed
        DB      00011100B   ;144 ê
        DB      00010000B
        DB      11111100B
        DB      01100000B
        DB      01111000B
        DB      01100000B
        DB      11111100B
        DB      00000000B
;
;       *** HEX 91 ***      changed
        DB      11001110B   ;145 ë
        DB      11001000B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      11111110B
        DB      00000000B
;
;       *** HEX 92 ***      CHANGED
        DB      11001110B   ;146 l acute
        DB      11001000B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      01111000B
        DB      00000000B
;
;       *** HEX 93 ***
        DB      01111000B   ;147 ì
        DB      11001100B
        DB      00000000B
        DB      01111000B
        DB      11001100B
        DB      11001100B
        DB      01111000B
        DB      00000000B
;
;       *** HEX 94 ***
        DB      11001100B   ;148 î
        DB      00000000B
        DB      01111000B
        DB      11001100B
        DB      11001100B
        DB      11001100B
        DB      01111000B
        DB      00000000B
;
;       *** HEX 95 ***      changed
        DB      11010010B   ;149 L caron
        DB      11001100B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      11111110B
        DB      00000000B
;
;       *** HEX 96 ***      changed
        DB      11010010B   ;150 l caron
        DB      11001100B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      11000000B
        DB      01111000B
        DB      00000000B
;
;       *** HEX 97 ***      CHANGED
        DB      00011100B   ;151 S ACUTE
        DB      00010000B
        DB      01111110B
        DB      11000000B
        DB      01111100B
        DB      00000110B
        DB      11111100B
        DB      00000000B
;
;       *** HEX 98 ***      changed
        DB      00011100B   ;152 s acute
        DB      00010000B
        DB      00111110B
        DB      01100000B
        DB      00111100B
        DB      00000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX 99 ***      changed
        DB      11000110B   ;153 ô
        DB      01111100B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX 9A ***      changed
        DB      11000110B   ;154 ö
        DB      00000000B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX 9B ***      changed
        DB      01001000B   ;155 T caron
        DB      00110000B
        DB      11111100B
        DB      00110000B
        DB      00110000B
        DB      00110000B
        DB      00110000B
        DB      00000000B
;
;       *** HEX 9C ***      changed
        DB      01001000B   ;156 t caron
        DB      00110000B
        DB      00110000B
        DB      11111100B
        DB      00110000B
        DB      00110000B
        DB      00011110B
        DB      00000000B
;
;       *** HEX 9D ***      chnaged
        DB      01100000B   ;157 L stroke
        DB      01101100B
        DB      01111000B
        DB      01110000B
        DB      01100000B
        DB      11100000B
        DB      01111110B
        DB      00000000B
;
;       *** HEX 9E ***
        DB      00000000B   ;158   multiply
        DB      11000110B
        DB      01101100B
        DB      00111000B
        DB      01101100B
        DB      11000110B
        DB      00000000B
        DB      00000000B
;
;       *** HEX 9F ***      chnaged
        DB      00100100B   ;159   c caron
        DB      00011000B
        DB      00111100B
        DB      01100110B
        DB      01100000B
        DB      01100110B
        DB      00111100B
        DB      00000000B
;
;       *** HEX A0 ***      changed
        DB      00011100B   ;160 †
        DB      00010000B
        DB      01111000B
        DB      00001100B
        DB      01111100B
        DB      11001100B
        DB      01111110B
        DB      00000000B
;
;       *** HEX A1 ***      changed
        DB      00011100B   ;161 °
        DB      00010000B
        DB      00111000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00111100B
        DB      00000000B
;
;       *** HEX A2 ***      changed
        DB      00000000B   ;162 ¢
        DB      00011100B
        DB      00010000B
        DB      01111000B
        DB      11001100B
        DB      11001100B
        DB      01111000B
        DB      00000000B
;
;       *** HEX A3 ***      changed
        DB      00000000B   ;163 £
        DB      00011100B
        DB      00010000B
        DB      11001100B
        DB      11001100B
        DB      11001100B
        DB      01111110B
        DB      00000000B
;
;       *** HEX A4 ***      changed
        DB      00111000B   ;164 A foot
        DB      01101100B
        DB      11000110B
        DB      11111110B
        DB      11000110B
        DB      11010110B
        DB      00001100B
        db      00001110b
;
;       *** HEX A5 ***      changed
        DB      00000000B   ;165 a foot
        DB      00000000B
        DB      01111000B
        DB      00001100B
        DB      01111100B
        DB      11001100B
        DB      01110110B
        DB      00001111B
;
;       *** HEX A6 ***      changed
        DB      00100100B   ;166 Z caron
        DB      00011000B
        DB      11111110B
        DB      00001100B
        DB      00011000B
        DB      01100000B
        DB      11111110B
        DB      00000000B
;
;       *** HEX A7 ***      chnaged
        DB      00100100B   ;167 z caron
        DB      00011000B
        DB      00000000B
        DB      01111110B
        DB      00001100B
        DB      00110000B
        DB      01111110B
        DB      00000000B
;
;       *** HEX A8 ***      changed
        DB      11111110B   ;168 E foot
        DB      11000000B
        DB      11000000B
        DB      11111000B
        DB      11000000B
        DB      11000000B
        DB      11111110B
        DB      00011100B
;
;       *** HEX A9 ***      changed
        DB      00000000B   ;169  e foot
        DB      00000000B
        DB      01111000B
        DB      11001100B
        DB      11111100B
        DB      11000000B
        DB      01111000B
        DB      00011100B
;

;       *** HEX AA ***      changed
        DB      00000000B   ;170  not defined
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX AB ***      changed
        DB      00011100B   ;171  z acute
        DB      00010000B
        DB      00000000B
        DB      01111110B
        DB      00001100B
        DB      00110000B
        DB      01111110B
        DB      00000000B
;
;       *** HEX AC ***      changed
        DB      00100100B   ;172  C caron
        DB      00011000B
        DB      01111100B
        DB      11000110B
        DB      11000000B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX AD ***      changed
        DB      00000000B   ;173 s foot
        DB      00000000B
        DB      00111100B
        DB      11000000B
        DB      01111000B
        DB      00001100B
        DB      11111000B
        DB      00111000B
;
;       *** HEX AE ***
        DB      00000000B   ;174   Æ
        DB      00110011B
        DB      01100110B
        DB      11001100B
        DB      01100110B
        DB      00110011B
        DB      00000000B
        DB      00000000B
;
;       *** HEX AF ***
        DB      00000000B   ;175 Ø    *
        DB      11001100B
        DB      01100110B
        DB      00110011B
        DB      01100110B
        DB      11001100B
        DB      00000000B
        DB      00000000B
;
;       *** HEX B0 ***
        DB      00100010B   ;176 ∞
        DB      10001000B
        DB      00100010B
        DB      10001000B
        DB      00100010B
        DB      10001000B
        DB      00100010B
        DB      10001000B
;
;       *** HEX B1 ***
        DB      01010101B   ;177 ±
        DB      10101010B
        DB      01010101B
        DB      10101010B
        DB      01010101B
        DB      10101010B
        DB      01010101B
        DB      10101010B
;
;       *** HEX B2 ***
        DB      11011011B   ;178 ≤
        DB      01110111B
        DB      11011011B
        DB      11101110B
        DB      11011011B
        DB      01110111B
        DB      11011011B
        DB      11101110B
;
;       *** HEX B3 ***
        DB      00011000B   ;179 ≥
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
;
;       *** HEX B4 ***
        DB      00011000B   ;180 ¥
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      11111000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
;
;       *** HEX B5 ***
        DB      00011100B   ;181 A grave
        DB      00010000B
        DB      01111100B
        DB      11000110B
        DB      11111110B
        DB      11000110B
        DB      11000110B
        DB      00000000B
;
;       *** HEX B6 ***
        DB      01111100B   ;182 A circumflex
        DB      10000010B
        DB      01111100B
        DB      11000110B
        DB      11111110B
        DB      11000110B
        DB      11000110B
        DB      00000000B
;
;       *** HEX B7 ***      changed
        DB      01001000B   ;183 E caron
        DB      00110000B
        DB      11111110B
        DB      11000000B
        DB      11111000B
        DB      11000000B
        DB      11111110B
        DB      00000000B
;
;       *** HEX B8 ***
        DB      01111000B   ;184 S foot
        DB      11001100B
        DB      01100000B
        DB      00110000B
        DB      00011000B
        DB      11001100B
        DB      01111000B
        DB      00110000B
;
;       *** HEX B9 ***
        DB      00110110B   ;185 π
        DB      00110110B
        DB      11110110B
        DB      00000110B
        DB      11110110B
        DB      00110110B
        DB      00110110B
        DB      00110110B
;
;       *** HEX BA ***
        DB      00110110B   ;186 ∫
        DB      00110110B
        DB      00110110B
        DB      00110110B
        DB      00110110B
        DB      00110110B
        DB      00110110B
        DB      00110110B
;
;       *** HEX BB ***
        DB      00000000B   ;187 ª
        DB      00000000B
        DB      11111110B
        DB      00000110B
        DB      11110110B
        DB      00110110B
        DB      00110110B
        DB      00110110B
;
;       *** HEX BC ***
        DB      00110110B   ;188 º
        DB      00110110B
        DB      11110110B
        DB      00000110B
        DB      11111110B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX BD ***
        DB      00011000B   ;189 Z overdot
        DB      11111110B
        DB      11000110B
        DB      00001100B
        DB      00110000B
        DB      11000110B
        DB      11111110B
        DB      00000000B
;
;       *** HEX BE ***      changed
        DB      00000000B   ;190 z overdot
        DB      00011000B
        DB      00000000B
        DB      01111100B
        DB      00011000B
        DB      00110000B
        DB      01111100B
        DB      00000000B
;
;       *** HEX BF ***
        DB      00000000B   ;191 ø
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      11111000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
;
;       *** HEX C0 ***
        DB      00011000B   ;192 ¿
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011111B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX C1 ***
        DB      00011000B   ;193 ¡
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      11111111B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX C2 ***
        DB      00000000B   ;194 ¬
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      11111111B
        DB      00011000B
        DB      00011000B
        DB      00011000B
;
;       *** HEX C3 ***
        DB      00011000B   ;195 √
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011111B
        DB      00011000B
        DB      00011000B
        DB      00011000B
;
;       *** HEX C4 ***
        DB      00000000B   ;196 ƒ
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      11111111B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX C5 ***
        DB      00011000B   ;197 ≈
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      11111111B
        DB      00011000B
        DB      00011000B
        DB      00011000B
;
;       *** HEX C6 ***      changed
        DB      11000110B   ;198 A breve
        DB      01111100B
        DB      01111100B
        DB      11000110B
        DB      11111110B
        DB      11000110B
        DB      11000110B
        DB      00000000B
;
;       *** HEX C7 ***      changed
        DB      11001100B   ;199 a breve
        DB      01111000B
        DB      01111000B
        DB      00001100B
        DB      01111100B
        DB      11001100B
        DB      01110110B
        DB      00000000B
;
;       *** HEX C8 ***
        DB      00110110B   ;200 »
        DB      00110110B
        DB      00110111B
        DB      00110000B
        DB      00111111B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX C9 ***
        DB      00000000B   ;201 …
        DB      00000000B
        DB      00111111B
        DB      00110000B
        DB      00110111B
        DB      00110110B
        DB      00110110B
        DB      00110110B
;
;       *** HEX CA ***
        DB      00110110B  ;202  
        DB      00110110B
        DB      11110111B
        DB      00000000B
        DB      11111111B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX CB ***
        DB      00000000B  ;203 À
        DB      00000000B
        DB      11111111B
        DB      00000000B
        DB      11110111B
        DB      00110110B
        DB      00110110B
        DB      00110110B
;
;       *** HEX CC ***
        DB      00110110B   ;204 Ã
        DB      00110110B
        DB      00110111B
        DB      00110000B
        DB      00110111B
        DB      00110110B
        DB      00110110B
        DB      00110110B
;
;       *** HEX CD ***
        DB      00000000B   ;205 Õ
        DB      00000000B
        DB      11111111B
        DB      00000000B
        DB      11111111B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX CE ***
        DB      00110110B  ;206 Œ
        DB      00110110B
        DB      11110111B
        DB      00000000B
        DB      11110111B
        DB      00110110B
        DB      00110110B
        DB      00110110B
;
;       *** HEX CF ***
        DB      00000000B   ;207 currency symbol
        DB      01000010B
        DB      00111100B
        DB      01100110B
        DB      01100110B
        DB      00111100B
        DB      01000010B
        DB      00000000B
;
;       *** HEX D0 ***      changed
        DB      00001100B   ;208 d dash
        DB      00111110B
        DB      00001100B
        DB      01111100B
        DB      11001100B
        DB      11001100B
        DB      01110110B
        DB      00000000B
;
;       *** HEX D1 ***      changed
        DB      01111100B   ;209 D dash
        DB      01100110B
        DB      01100110B
        DB      11110110B
        DB      01100110B
        DB      01100110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX D2 ***      changed
        DB      01001000B   ;210 D caron
        DB      00110000B
        DB      11111100B
        DB      01100110B
        DB      01100110B
        DB      01100110B
        DB      11111100B
        DB      00000000B
;
;       *** HEX D3 ***
        DB      11001100B   ;211 ”
        DB      00000000B
        DB      11111100B
        DB      01100000B
        DB      01111000B
        DB      01100000B
        DB      11111100B
        DB      00000000B
;
;       *** HEX D4 ***      changed
        DB      10010110B   ;212 d caron
        DB      01100110B
        DB      00000110B
        DB      01111110B
        DB      11000110B
        DB      11000110B
        DB      01111110B
        DB      00000000B
;
;       *** HEX D5 ***      changed
        DB      00100100B   ;213 N caron
        DB      00011000B
        DB      11100110B
        DB      11110110B
        DB      11011110B
        DB      11001110B
        DB      11000110B
        DB      00000000B
;
;       *** HEX D6 ***
        DB      00011100B   ;214 I acute
        DB      00010000B
        DB      01111000B
        DB      00110000B
        DB      00110000B
        DB      00110000B
        DB      01111000B
        DB      00000000B
;
;       *** HEX D7 ***
        DB      01111000B   ;215 I Circumflex
        DB      10000100B
        DB      01111000B
        DB      00110000B
        DB      00110000B
        DB      00110000B
        DB      01111000B
        DB      00000000B
;
;       *** HEX D8 ***      changed
        DB      01001000B   ;216 e caron
        DB      00110000B
        DB      01111000B
        DB      11001100B
        DB      11111100B
        DB      11000000B
        DB      01111000B
        DB      00000000B
;
;       *** HEX D9 ***
        DB      00011000B   ;217 Ÿ
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      11111000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX DA ***
        DB      00000000B  ;218 ⁄
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00011111B
        DB      00011000B
        DB      00011000B
        DB      00011000B
;
;       *** HEX DB ***
        DB      11111111B   ;219 €
        DB      11111111B
        DB      11111111B
        DB      11111111B
        DB      11111111B
        DB      11111111B
        DB      11111111B
        DB      11111111B
;
;       *** HEX DC ***
        DB      00000000B  ;220 ‹
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      11111111B
        DB      11111111B
        DB      11111111B
        DB      11111111B
;
;       *** HEX DD ***      changed
        DB      01111110B   ;221 T foot
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00011000B
        DB      00001110B
;
;       *** HEX DE ***      chnaged
        DB      00010000B   ;222 U circle
        DB      00101000B
        DB      11010110B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX DF ***
        DB      11111111B   ;223 ﬂ
        DB      11111111B
        DB      11111111B
        DB      11111111B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX E0 ***      changed
        DB      00011100B   ;224 O acute
        DB      00010000B
        DB      01111100B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX E1 ***
        DB      00000000B   ;225 ·
        DB      01111000B
        DB      11001100B
        DB      11111000B
        DB      11001100B
        DB      11111000B
        DB      11000000B
        DB      11000000B
;
;       *** HEX E2 ***      changed
        DB      01111100B   ;226 O circumflex
        DB      10000010B
        DB      01111100B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX E3 ***     changed
        DB      00011100B   ;227 N acute
        DB      00010000B
        DB      11100110B
        DB      11110110B
        DB      11011110B
        DB      11001110B
        DB      11000110B
        DB      00000000B
;
;       *** HEX E4 ***      changed
        DB      00011100B   ;228 n acute
        DB      00010000B
        DB      11011100B
        DB      11100110B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      00000000B
;
;       *** HEX E5 ***      changed
        DB      00100100B   ;228 n caron
        DB      00011000B
        DB      11011100B
        DB      11100110B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      00000000B
;
;       *** HEX E6 ***      changed
        DB      01001000B   ;230 S caron
        DB      00110000B
        DB      01111110B
        DB      11100000B
        DB      00111000B
        DB      00001110B
        DB      11111100B
        DB      00000000B
;
;       *** HEX E7 ***      changed
        DB      01001000B   ;231 s caron
        DB      00110000B
        DB      01111100B
        DB      01000000B
        DB      00111000B
        DB      00000100B
        DB      01111100B
        DB      00000000B
;
;       *** HEX E8 ***      changed
        DB      00011100B   ;232 R acute
        DB      00010000B
        DB      11111100B
        DB      11000110B
        DB      11111100B
        DB      11011000B
        DB      11001100B
        DB      00000000B
;
;       *** HEX E9 ***      chnaged
        DB      00001110B   ;233 U acute
        DB      00001000B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX EA ***      changed
        DB      00111000B   ;234 r acute
        DB      00100000B
        DB      11001110B
        DB      11110000B
        DB      11100000B
        DB      11000000B
        DB      11000000B
        DB      00000000B
;
;       *** HEX EB ***      changed
        DB      11101110B   ;235 U dbl acute
        DB      10001000B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      11000110B
        DB      01111100B
        DB      00000000B
;
;       *** HEX EC ***      chnaged
        DB      00011100B   ;236 y acute
        DB      00010000B
        DB      11000110B
        DB      11000110B
        DB      01100110B
        DB      00111110B
        DB      00001100B
        DB      01111000B
;
;       *** HEX ED ***      changed
        DB      00011100B   ;237 Y acute
        DB      11010110B
        DB      11000110B
        DB      01100110B
        DB      00111100B
        DB      00011000B
        DB      00110000B
        DB      00000000B
;
;       *** HEX EE ***      chnaged
        DB      00110000B   ;238 t foot
        DB      01111000B
        DB      00110000B
        DB      00110000B
        DB      00110000B
        DB      00110000B
        DB      00011100B
        DB      00001110B
;
;       *** HEX EF ***      changed
        DB      00001110B   ;239 acute
        DB      00001000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX F0 ***
        DB      00000000B   ;240 minus
        DB      00000000B
        DB      00000000B
        DB      00111100B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX F1 ***      chnaged
        DB      11101110B   ;241 dbl acute
        DB      10001000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX F2 ***
        DB      00000000B   ;242 foot
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00010000B
        DB      00011100B
;
;       *** HEX F3 ***      changed
        DB      01001000B   ;243 caron
        DB      00110000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX F4 ***      changed
        DB      11000110B   ;244 breve
        DB      01111100B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX F5 ***
        DB      00111110B   ;245 paragraph
        DB      01100011B
        DB      00111000B
        DB      01101100B
        DB      01101100B
        DB      00111000B
        DB      11001100B
        DB      01111000B
;
;       *** HEX F6 ***
        DB      00011000B   ;246 divide
        DB      00011000B
        DB      00000000B
        DB      01111110B
        DB      00000000B
        DB      00011000B
        DB      00011000B
        DB      00000000B
;
;       *** HEX F7 ***      changed
        DB      00000000B   ;247 foot
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000100B
        DB      00011100B
;
;       *** HEX F8 ***       changed
        DB      00111000B   ;248 circle
        DB      01101100B
        DB      01101100B
        DB      00111000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX F9 ***      changed
        DB      01100110B   ;249 umlaut
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX FA ***      chnaged
        DB      00011000B   ;250 overdot
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;
;       *** HEX FB ***      changed
        DB      11101110B   ;251 u dbl acute
        DB      10001000B
        DB      11001100B
        DB      11001100B
        DB      11001100B
        DB      11001100B
        DB      01110110B
        DB      00000000B
;
;       *** HEX FC ***      changed
        DB      01001000B   ;252 R caron
        DB      00110000B
        DB      11111100B
        DB      11000110B
        DB      11111100B
        DB      11011000B
        DB      11001100B
        DB      00000000B
;
;       *** HEX FD ***      changed
        DB      01001000B   ;253 r caron
        DB      00110000B
        DB      11001110B
        DB      11011000B
        DB      11100000B
        DB      11000000B
        DB      11000000B
        DB      00000000B
.LIST
;
;       *** HEX FE ***
        DB      00000000B   ;254 ˛
        DB      00000000B
        DB      00111100B
        DB      00111100B
        DB      00111100B
        DB      00111100B
        DB      00000000B
        DB      00000000B
;
;       *** HEX FF ***
        DB      00000000B   ;255
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
        DB      00000000B
;


	DW	852			 ;TABLE ID
	DB	"Latin-2",0		 ;LANGUAGE NAME, IN ASCIIZ FORMAT
	IF	($-CSEG) MOD 16 	 ;IF NOT ALREADY ON 16 BYTE BOUNDARY
	    DB	    (16-(($-CSEG) MOD 16)) DUP(0)  ;ADD PADDING TO GET TO 16 BYTE BOUNDARY
	ENDIF
CSEG	ENDS
	END

